# Generated by Django 5.2.15 on 2026-06-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_english_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ('-created_at',), 'verbose_name': 'رسالة تواصل', 'verbose_name_plural': 'رسائل التواصل'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('sort_order',), 'verbose_name': 'سؤال شائع', 'verbose_name_plural': 'الأسئلة الشائعة'},
        ),
        migrations.AlterModelOptions(
            name='showroom',
            options={'ordering': ('sort_order',), 'verbose_name': 'معرض', 'verbose_name_plural': 'المعارض'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='inquiry_type',
            field=models.CharField(choices=[('general', 'General'), ('order', 'Order'), ('custom', 'Custom'), ('wholesale', 'Wholesale'), ('returns', 'Returns'), ('artisan', 'Artisan')], default='general', max_length=20, verbose_name='نوع الاستفسار'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='مقروءة'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(blank=True, max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=300, verbose_name='الموضوع'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ar',
            field=models.TextField(verbose_name='الإجابة'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ar',
            field=models.CharField(max_length=500, verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='address_ar',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='city_ar',
            field=models.CharField(max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='hours_ar',
            field=models.CharField(max_length=200, verbose_name='ساعات العمل'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='note_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
    ]
