# Generated by Django 6.0.6 on 2026-06-16 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('body_ar', models.TextField()),
                ('body_en', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Principle',
                'verbose_name_plural': 'Principles',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Star rating from 1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('body_ar', models.TextField()),
                ('body_en', models.TextField(blank=True)),
                ('client_name_ar', models.CharField(max_length=120)),
                ('client_name_en', models.CharField(blank=True, max_length=120)),
                ('location_ar', models.CharField(blank=True, max_length=120)),
                ('location_en', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Curated display order (lower = first). Ties fall back to newest.')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
    ]
