# Generated by Django 5.2.15 on 2026-06-22 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_english_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principle',
            options={'ordering': ('sort_order',), 'verbose_name': 'مبدأ', 'verbose_name_plural': 'المبادئ'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('sort_order', '-created_at'), 'verbose_name': 'تقييم العملاء', 'verbose_name_plural': 'تقييمات العملاء'},
        ),
        migrations.AlterField(
            model_name='principle',
            name='body_ar',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='principle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='principle',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='principle',
            name='title_ar',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=True, verbose_name='معتمد'),
        ),
        migrations.AlterField(
            model_name='review',
            name='body_ar',
            field=models.TextField(verbose_name='التعليق'),
        ),
        migrations.AlterField(
            model_name='review',
            name='client_name_ar',
            field=models.CharField(max_length=120, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='review',
            name='location_ar',
            field=models.CharField(blank=True, max_length=120, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Star rating from 1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Curated display order (lower = first). Ties fall back to newest.', verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='review',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='موثق'),
        ),
    ]
