# Generated by Django 5.2.15 on 2026-06-22 21:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_english_fields'),
        ('orders', '0002_remove_english_fields'),
        ('shop', '0016_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'عنصر الطلب', 'verbose_name_plural': 'عناصر الطلب'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line',
            field=models.CharField(max_length=400, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.cart', verbose_name='السلة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='DA', max_length=10, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total_da',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المجموع الكلي (دج)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_da',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الشحن (دج)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغى')], default='pending', max_length=15, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_da',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المجموع الجزئي (دج)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name_snapshot_ar',
            field=models.CharField(blank=True, max_length=220, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sku_snapshot',
            field=models.CharField(blank=True, max_length=64, verbose_name='رمز المنتج'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_da_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة (دج)'),
        ),
    ]
