# Generated by Django 5.2.15 on 2026-06-15 17:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/categories/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (smaller values shown first).')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Promote to landing page category rails.')),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent category — supports a two-level hierarchy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('sku', models.CharField(help_text='Stock Keeping Unit — internal unique identifier.', max_length=64, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='Shown in product card / list views.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Full product narrative.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Current selling price (in DA).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Strike-through price — when set, the product displays as on sale.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Internal cost for margin reporting.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=3, help_text="When stock falls below this, availability flips to 'low stock'.")),
                ('track_inventory', models.BooleanField(default=True)),
                ('availability', models.CharField(choices=[('in_stock', 'In stock'), ('low_stock', 'Low stock'), ('out_of_stock', 'Out of stock'), ('discontinued', 'Discontinued'), ('pre_order', 'Pre-order')], default='in_stock', max_length=20)),
                ('origin', models.CharField(blank=True, help_text="Place + material, e.g. 'Tlemcen · Pure Wool'.", max_length=120)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('care_instructions', models.TextField(blank=True)),
                ('weight_grams', models.PositiveIntegerField(blank=True, help_text='Product weight in grams.', null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, help_text='Primary product image shown on listing cards.', null=True, upload_to='shop/products/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False, help_text="Surface under 'New Arrivals'.")),
                ('is_limited', models.BooleanField(default=False, help_text='Mark as limited-edition piece.')),
                ('badge', models.CharField(blank=True, choices=[('', 'None'), ('new', 'New'), ('sale', 'Sale'), ('limited', 'Limited'), ('bestseller', 'Bestseller')], default='', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cached average rating 0.00 – 5.00.', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('sales_count', models.PositiveIntegerField(default=0, help_text='Cached total units sold (for bestsellers).')),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ('-created_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='shop/products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'order'], name='shop_catego_is_acti_bde3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category'], name='shop_produc_is_acti_6b3eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='shop_produc_is_feat_a70478_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['availability'], name='shop_produc_availab_5f9719_idx'),
        ),
    ]
