# Generated by Django 5.2.15 on 2026-06-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_english_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, help_text='Full product narrative in Arabic.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_ar',
            field=models.CharField(blank=True, help_text='Short description in Arabic.', max_length=255),
        ),
    ]
