# Generated by Django 5.2.15 on 2026-06-22 15:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_available_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order', 'name_ar'), 'verbose_name': 'فئة', 'verbose_name_plural': 'الفئات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at', 'name_ar'), 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('order', 'id'), 'verbose_name': 'صورة المنتج', 'verbose_name_plural': 'صور المنتج'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ('-created_at',), 'verbose_name': 'تقييم المنتج', 'verbose_name_plural': 'تقييمات المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='wilaya',
            options={'ordering': ('code',), 'verbose_name': 'ولاية', 'verbose_name_plural': 'الولايات'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/categories/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Promote to landing page category rails.', verbose_name='مميز'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='وصف SEO'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=120, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (smaller values shown first).', verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.category', verbose_name='الفئة الأم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('low_stock', 'Low stock'), ('out_of_stock', 'Out of stock'), ('discontinued', 'Discontinued'), ('pre_order', 'Pre-order')], default='in_stock', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('', 'None'), ('new', 'New'), ('sale', 'Sale'), ('limited', 'Limited'), ('bestseller', 'Bestseller')], default='', max_length=20, verbose_name='الشارة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, verbose_name='تعليمات العناية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internal cost for margin reporting.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر التكلفة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='الوصف الكامل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, help_text='Product details — one bullet point per line (used in the Details tab).', verbose_name='التفاصيل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الارتفاع (سم)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/products/', verbose_name='الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (used when no uploaded image is present).', verbose_name='رابط الصورة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_limited',
            field=models.BooleanField(default=False, help_text='Mark as limited-edition piece.', verbose_name='محدود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, help_text="Surface under 'New Arrivals'.", verbose_name='جديد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الطول (سم)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=3, help_text="When stock falls below this, availability flips to 'low stock'.", verbose_name='حد المخزون المنخفض'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=120, verbose_name='الخامة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='وصف SEO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=220, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Strike-through price — when set, the product displays as on sale.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='السعر القديم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, help_text="Place + material, e.g. 'Tlemcen · Pure Wool'.", max_length=120, verbose_name='المنشأ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Current selling price (in DA).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cached average rating 0.00 – 5.00.', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached total units sold (for bestsellers).', verbose_name='عدد المبيعات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='وصف مختصر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Stock Keeping Unit — internal unique identifier.', max_length=64, unique=True, verbose_name='رمز المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=240, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية في المخزون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True, verbose_name='تتبع المخزون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الوزن (غرام)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='العرض (سم)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=160, verbose_name='نص بديل'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='shop/products/gallery/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='body',
            field=models.TextField(blank=True, verbose_name='التعليق'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Only approved reviews appear publicly and count toward the rating.', verbose_name='معتمد'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='shop.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Rating from 1 (worst) to 5 (best).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='reviewer_name',
            field=models.CharField(max_length=120, verbose_name='اسم المقيّم'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='code',
            field=models.PositiveIntegerField(help_text='Wilaya code 1–58.', unique=True, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='الاسم بالعربية'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name_fr',
            field=models.CharField(max_length=100, verbose_name='الاسم بالفرنسية'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='shipping_price_da',
            field=models.DecimalField(decimal_places=2, default=700, max_digits=8, verbose_name='سعر الشحن (دج)'),
        ),
    ]
