from django.db import migrations

# (wilaya_code, [(name_ar, name_fr), ...])
BALADIAS = [
    (1, [  # Adrar
        ("أدرار", "Adrar"), ("أولف", "Aoulef"), ("تيميمون", "Timimoun"),
        ("تمنطيط", "Tamentit"), ("فنوغيل", "Fenoughil"), ("رقان", "Reggane"),
        ("أولاد سعيد", "Ouled Saïd"), ("زاوية كنتة", "Zaouiet Kounta"),
        ("أوقروت", "Aougrout"), ("تصابيت", "Tsabit"), ("متارفة", "Metarfa"),
        ("صالح", "Sali"), ("أقبلي", "Akabli"), ("تامست", "Tamest"),
        ("شاروين", "Charouine"), ("دلدول", "Deldoul"), ("تينركوك", "Tinerkouk"),
        ("قصر قدور", "Ksar Kaddour"), ("أولاد عيسى", "Ouled Aïssa"),
        ("بودة", "Bouda"), ("عين زغير", "Aïn Zgheur"),
    ]),
    (2, [  # Chlef
        ("الشلف", "Chlef"), ("تنس", "Ténès"), ("عين مران", "Aïn Merane"),
        ("القريمية", "El Karimia"), ("زبوجة", "Zeboudja"), ("أولاد فارس", "Ouled Farès"),
        ("صبحة", "Sobha"), ("حرشون", "Harchoun"), ("وادي الفضة", "Oued El Fodda"),
        ("بوزغاية", "Bouzghaia"), ("أبو الحسن", "Abou El Hassan"),
        ("برج بونعامة", "Bordj Bou Naama"), ("المرسى", "El Marsa"),
        ("بني راشد", "Beni Rached"), ("تاجنة", "Tadjna"),
        ("بنايرية", "Bénairia"), ("حيدوسة", "Haïdous"),
    ]),
    (3, [  # Laghouat
        ("الأغواط", "Laghouat"), ("أفلو", "Aflou"), ("عين ماضي", "Aïn Madhi"),
        ("حاسي الرمل", "Hassi Rmel"), ("وادي مرة", "Oued Morra"),
        ("قصر الهيران", "Ksar El Hirane"), ("السبعة", "El Ghicha"),
        ("الحاج المشري", "El Hadj Mechri"), ("برج الدويرة", "Tadjmout"),
        ("تاجموت", "Tadjmout"), ("سبقاق", "Sebgag"),
        ("بريدة", "Brida"), ("عين سيدي علي", "Aïn Sidi Ali"),
    ]),
    (4, [  # Oum El Bouaghi
        ("أم البواقي", "Oum El Bouaghi"), ("عين البيضاء", "Aïn Beïda"),
        ("عين مليلة", "Aïn M'lila"), ("سوق نعمان", "Souk Naamane"),
        ("عين فكرون", "Aïn Fakroun"), ("سيقوس", "Sigus"),
        ("الأميرية", "El Amiria"), ("فكيرينة", "Fkirina"),
        ("عين الديس", "Aïn El Diss"), ("المسكيانة", "Meskiana"),
        ("أولاد حميمة", "Ouled Hamla"), ("هنشير تومغني", "Henchir Toumghani"),
    ]),
    (5, [  # Batna
        ("باتنة", "Batna"), ("باريكة", "Barika"), ("عين توتة", "Aïn Touta"),
        ("آريس", "Arris"), ("مروانة", "Merouana"), ("تازولت", "Tazoult"),
        ("نقاوس", "N'Gaous"), ("رأس العيون", "Ras El Aïoun"),
        ("تيمقاد", "Timgad"), ("سريانة", "Seriana"), ("منعة", "Menaa"),
        ("الشمرة", "Chemora"), ("بريكة", "Brika"), ("وادي الشعبة", "Oued El Chaaba"),
        ("جرما", "Djerma"), ("فسديس", "Fesdis"), ("أولاد سي سليمان", "Ouled Si Slimane"),
        ("بيطام", "Bittam"), ("بومقر", "Boumagueur"),
    ]),
    (6, [  # Béjaïa
        ("بجاية", "Béjaïa"), ("أقبو", "Akbou"), ("تازمالت", "Tazmalt"),
        ("القصر", "El Kseur"), ("أميزور", "Amizour"), ("سوق التنين", "Souk El Ténine"),
        ("تيشي", "Tichy"), ("أوقاس", "Aokas"), ("سيدي عيش", "Sidi Aïch"),
        ("أدكار", "Adekar"), ("خراطة", "Kherrata"), ("بني كسيلة", "Beni Ksila"),
        ("إيغيل أعلي", "Ighil Ali"), ("بني معوش", "Beni Maouche"),
        ("تاسكريوت", "Taskériout"), ("أوزلاقن", "Ouzlaguen"),
        ("التلاغمة", "Tala Hamza"), ("بجاية", "Tichy"),
        ("الفلاي", "El Flaye"), ("بني جليل", "Beni Djelil"),
    ]),
    (7, [  # Biskra
        ("بسكرة", "Biskra"), ("طولقة", "Tolga"), ("القنطرة", "El Kantara"),
        ("سيدي عقبة", "Sidi Okba"), ("زريبة الوادي", "Zéribet El Oued"),
        ("عين ناقة", "Aïn Naga"), ("الوطاية", "El Outaya"),
        ("شتمة", "Chetma"), ("اورلال", "Ourlal"), ("أولاد جلال", "Ouled Djellal"),
        ("الدوسن", "El Doucen"), ("ليشانة", "Lichana"),
        ("جمورة", "Djemorah"), ("المزيرعة", "El Mizaraa"),
        ("مشونش", "Mchouneche"), ("رأس الميعاد", "Ras El Miaa"),
    ]),
    (8, [  # Béchar
        ("بشار", "Béchar"), ("كنادسة", "Kenadsa"), ("لحمر", "Lahmar"),
        ("تاغيت", "Taghit"), ("إيقلي", "Igli"), ("بوكايس", "Boukais"),
        ("مريجة", "Mérija"), ("ابلا", "Abadla"),
        ("تيموديلين", "Timoudi"), ("واد النمس", "Oued El Namous"),
    ]),
    (9, [  # Blida
        ("البليدة", "Blida"), ("بوفاريك", "Boufarik"), ("الأربعاء", "Larbaâ"),
        ("بوقرة", "Bougara"), ("مفتاح", "Meftah"), ("شريعة", "Chréa"),
        ("بني تامو", "Beni Tamou"), ("وادي العلايق", "Oued El Alleug"),
        ("بن خليل", "Ben Khellil"), ("العفرون", "El Affroun"),
        ("بوينان", "Bouinan"), ("بني مراد", "Béni Mered"),
        ("موزاية", "Mouzaïa"), ("وادي جر", "Oued Djer"),
        ("بن بولعيد", "Aïn Romana"), ("صوالح", "Soumaâ"),
    ]),
    (10, [  # Bouira
        ("البويرة", "Bouira"), ("عين بسام", "Aïn Bessem"),
        ("الأخضرية", "Lakhdaria"), ("سور الغزلان", "Sour El Ghozlane"),
        ("قادرية", "Kadiria"), ("المشدالة", "M'chedallah"),
        ("بشلول", "Bechloul"), ("الحشيمية", "El Hachimia"),
        ("مسبوح", "Maâla"), ("عمر شريف", "Aomar"),
        ("الحجرة", "Haïzer"), ("بئر غبالو", "Bir Ghbalou"),
    ]),
    (11, [  # Tamanrasset
        ("تمنراست", "Tamanrasset"), ("أبلسة", "Abalessa"),
        ("تازروك", "Tazrouk"), ("إيدلس", "Idles"),
        ("عين أمقل", "In Amguel"),
    ]),
    (12, [  # Tébessa
        ("تبسة", "Tébessa"), ("الشريعة", "Cheria"), ("العوينات", "El Aouinet"),
        ("حمام باريجة", "Hammamet"), ("بئر العاتر", "Bir El Ater"),
        ("العقلة", "El Ogla"), ("مسارة", "Mesaraa"),
        ("الونزة", "El Ouenza"), ("بئر ضباب", "Bir Dheb"),
        ("بولحاف الدير", "Boulhaf Dyr"), ("عين الزرقة", "Aïn Zerga"),
        ("فركان", "Ferkane"), ("قصر يلاس", "Ksar Yela"), ("الماء الأبيض", "El Mâ El Beïda"),
    ]),
    (13, [  # Tlemcen
        ("تلمسان", "Tlemcen"), ("مغنية", "Maghnia"), ("غزوات", "Ghazaouet"),
        ("ندرومة", "Nedroma"), ("رمشي", "Remchi"), ("سبدو", "Sebdou"),
        ("بنسكران", "Bensekrane"), ("أولاد ميمون", "Ouled Mimoun"),
        ("هونين", "Honaine"), ("عين فزة", "Aïn Fezza"),
        ("منصورة", "Mansourah"), ("بني صاف", "Béni Saf"),
        ("سوق ثلاثاء", "Souk Tlata"), ("فلاوسن", "Fellaoucène"),
        ("أولاد رياح", "Ouled Riah"), ("تيرني", "Tierni"),
        ("سبعة شيوخ", "Sebâa Chioukh"), ("بني خلاد", "Beni Khellad"),
        ("عين يوسف", "Aïn Youcef"), ("الرمشي", "Aïn Tallout"),
    ]),
    (14, [  # Tiaret
        ("تيارت", "Tiaret"), ("سوقر", "Sougueur"), ("فرندة", "Frenda"),
        ("قصر الشلالة", "Ksar Chellala"), ("مهدية", "Mehdia"),
        ("نايمة", "Naïma"), ("رحوية", "Rahouia"),
        ("الدحموني", "Dahmouni"), ("حمادية", "Hamadia"),
        ("السبت", "Es Sebt"), ("مشرع الصفا", "Mechraa Safa"),
        ("تخمارت", "Takhemaret"), ("وادي ليلى", "Oued Lilli"),
        ("وادي بقرة", "Meghila"), ("أولاد جلال", "Aïn Kermes"),
    ]),
    (15, [  # Tizi Ouzou
        ("تيزي وزو", "Tizi Ouzou"), ("عزازقة", "Azazga"),
        ("عين الحمام", "Aïn El Hammam"), ("أغريب", "Aghribs"),
        ("دراع الميزان", "Draâ El Mizan"), ("بوغني", "Boghni"),
        ("ماكودة", "Makouda"), ("تيقزيرت", "Tigzirt"),
        ("دراع بن خدة", "Draa Ben Khedda"), ("لربعاء ناث إيراثن", "Larbaa Nath Irathen"),
        ("بني دوالة", "Beni Douala"), ("واضية", "Ouadhia"),
        ("بوزقن", "Bouzeguène"), ("فريحة", "Fréha"),
        ("عين الزاوية", "Aïn Zaouïa"), ("إيلولة أومالو", "Iloula Oumalou"),
        ("مقلع", "Maâtkas"), ("أيت يحيى", "Aïth Yahia"),
        ("تادمايت", "Tadmait"), ("سي منصور", "Si Mustapha"),
    ]),
    (16, [  # Alger
        ("الجزائر الوسطى", "Alger-Centre"), ("سيدي مهمد", "Sidi M'Hamed"),
        ("المدنية", "El Madania"), ("بلوزداد", "Belouizdad"),
        ("باب الواد", "Bab El Oued"), ("بلوزداد", "Bologhine Ibn Ziri"),
        ("القصبة", "Casbah"), ("وادي قريش", "Oued Koriche"),
        ("بير مراد رايس", "Bir Mourad Raïs"), ("الأبيار", "El Biar"),
        ("بوزريعة", "Bouzareah"), ("بئر خادم", "Birkhadem"),
        ("الحراش", "El Harrach"), ("براقي", "Baraki"),
        ("وادي سمار", "Oued Smar"), ("باش جراح", "Bachdjerrah"),
        ("حسين داي", "Hussein Dey"), ("قوبة", "Kouba"),
        ("بوروبة", "Bourouba"), ("دار البيضاء", "Dar El Beïda"),
        ("باب الزوار", "Bab Ezzouar"), ("بن عكنون", "Ben Aknoun"),
        ("دالي إبراهيم", "Dely Ibrahim"), ("حمامات الضلعة", "Hammamet"),
        ("رايس حميدو", "Raïs Hamidou"), ("جسر قسنطينة", "Djasr El Abiod"),
        ("دويرة", "Douera"), ("بابا حسن", "Baba Hassen"),
        ("خرايسية", "Khraïcia"), ("صوالح", "Saoula"),
        ("عين البنيان", "Ain Benian"), ("ستاوالي", "Staoueli"),
        ("زرالدة", "Zeralda"), ("ماهلمة", "Mahelma"),
        ("الرحمانية", "Rahmania"), ("السويدانية", "Souidania"),
        ("شراقة", "Cheraga"), ("أولاد فايت", "Ouled Fayet"),
        ("الأشور", "El Achour"), ("دراريا", "Draria"),
    ]),
    (17, [  # Djelfa
        ("الجلفة", "Djelfa"), ("عين وسارة", "Aïn Oussera"),
        ("مسعد", "Messaad"), ("الشارف", "Charef"),
        ("حاسي بحبح", "Hassi Bahbah"), ("مليليحة", "M'liliha"),
        ("العيدلية", "El Idrissia"), ("بيرين", "Birine"),
        ("عين الإبل", "Aïn El Ibel"), ("سد الرحال", "Sidi Ladjel"),
        ("دار الشيوخ", "Dar Chioukh"), ("حاسي العش", "Hassi El Euch"),
        ("فيض البطمة", "Faidh El Botma"),
    ]),
    (18, [  # Jijel
        ("جيجل", "Jijel"), ("الميلية", "El Milia"),
        ("الطاهير", "Taher"), ("شقفة", "Chekfa"),
        ("زيامة منصورية", "Ziama Mansouriah"), ("تكسنة", "Texenna"),
        ("سيدي معروف", "Sidi Maarouf"), ("بوراوي بلهادف", "Bouraoui Belhadef"),
        ("القنار نشفي", "El Kennar Nouchfi"), ("الجمعة بني حبيبي", "Djemaa Beni Habibi"),
        ("عوانة", "Ouaouane"), ("أولاد رابح", "Ouled Rabia"),
    ]),
    (19, [  # Sétif
        ("سطيف", "Sétif"), ("العلمة", "El Eulma"),
        ("عين الكبيرة", "Aïn El Kebira"), ("بوقاعة", "Bougaa"),
        ("عين أرنات", "Aïn Arnat"), ("صالح باي", "Salah Bey"),
        ("عين أولمان", "Aïn Oulmane"), ("بني عزيز", "Béni Aziz"),
        ("الورسياس", "El Ouricia"), ("برج الغدير", "Béni Chebana"),
        ("أملاغمة", "Amoucha"), ("عين التين", "Aïn El Louh"),
        ("بابور", "Babor"), ("قجال", "Guejel"),
        ("تيزي نبشار", "Tizi N'Bechar"), ("أيت نواعمة", "Aït Noualha"),
        ("مزلوق", "Mezloug"), ("رأس الواد", "Ras El Oued"),
        ("المعذرة", "El Maadhid"), ("بئر العرش", "Bir El Arch"),
        ("قصور الولاية", "Ouldja Boulboul"),
    ]),
    (20, [  # Saïda
        ("سعيدة", "Saïda"), ("عين الحجر", "Aïn El Hadjar"),
        ("سيدي بوبكر", "Sidi Boubekeur"), ("يوب", "Youb"),
        ("أولاد إبراهيم", "Ouled Brahim"), ("الحساسنة", "El Hassasna"),
        ("تيرارا", "Tircine"), ("سيدي أحمد", "Sidi Ahmed"),
    ]),
    (21, [  # Skikda
        ("سكيكدة", "Skikda"), ("عزابة", "Azzaba"),
        ("القل", "Collo"), ("الحروش", "El Harrouch"),
        ("طمالوس", "Tamalous"), ("بن عزوز", "Ben Azzouz"),
        ("رمضان جمال", "Ramdane Djamel"), ("عين قشرة", "Ain Kechra"),
        ("عين شارب", "Aïn Cherchar"), ("فلفلة", "Filfila"),
        ("زيغود يوسف", "Zighoud Youcef"), ("القنواع", "El Hadaïek"),
        ("مجاز عمار", "Oum Toub"),
    ]),
    (22, [  # Sidi Bel Abbès
        ("سيدي بلعباس", "Sidi Bel Abbès"), ("رأس الماء", "Ras El Ma"),
        ("سفيزف", "Sfisef"), ("تسالة", "Tessala"),
        ("عين البرد", "Aïn El Berd"), ("تلاغ", "Telagh"),
        ("بن بادس", "Ben Badis"), ("تنيرة", "Tenira"),
        ("مرحوم", "Marhoum"), ("محمودية", "Mcid"),
        ("سيدي خالد", "Bir El Hammam"), ("عين تيدمين", "Aïn Tidamine"),
        ("بلعربي", "Belarbi"), ("مزاورو", "Mezaourou"),
    ]),
    (23, [  # Annaba
        ("عنابة", "Annaba"), ("عين الباردة", "Ain Berda"),
        ("بربال", "Berrahal"), ("شطايبي", "Chetaïbi"),
        ("البوني", "El Bouni"), ("الحجار", "El Hadjar"),
        ("سيدي عمار", "Sidi Amar"), ("عين صفراء", "Aïn El Berda"),
    ]),
    (24, [  # Guelma
        ("قالمة", "Guelma"), ("بوشقوف", "Bouchegouf"),
        ("حمام مسخوطين", "Hammam Meskhoutine"), ("هليوبوليس", "Héliopolis"),
        ("وادي الزناتي", "Oued Zenati"), ("عين بن بيضاء", "Ain Ben Beida"),
        ("قلعة بوزبار", "Guelaat Bou Sbaa"), ("حمام النبايل", "Hammam N'Bails"),
        ("بوحمدان", "Bouhamdane"), ("نشمايا", "Nechmaya"),
        ("بوعاتي محمود", "Bouati Mahmoud"),
    ]),
    (25, [  # Constantine
        ("قسنطينة", "Constantine"), ("عين عبيد", "Aïn Abid"),
        ("الخروب", "El Khroub"), ("حامة بوزيان", "Hamma Bouziane"),
        ("ابن بادس", "Ibn Badis"), ("ديدوش مراد", "Didouche Mourad"),
        ("زيغود يوسف", "Zighoud Youcef"), ("مسيد", "Ouled Rahmoun"),
        ("بني حميدان", "Beni Hamidane"),
    ]),
    (26, [  # Médéa
        ("المدية", "Médéa"), ("عين بوسيف", "Aïn Boucif"),
        ("برواقية", "Berrouaghia"), ("قصر البخاري", "Ksar El Boukhari"),
        ("تابلاط", "Tablat"), ("بني سليمان", "Beni Slimane"),
        ("العزيزية", "Aziz"), ("العمارية", "El Omaria"),
        ("شلالة العذاورة", "Chellalat El Adhaoura"), ("أولاد علال", "Ouled Maaref"),
        ("سوق الحد", "Souk El Had"), ("الربعية", "Rebaia"),
        ("بجاية", "Benchicao"), ("بو عيسى خليفة", "Bou Aïssa Khelifa"),
        ("الحمدانية", "Hamdania"),
    ]),
    (27, [  # Mostaganem
        ("مستغانم", "Mostaganem"), ("عين تادلس", "Aïn Tédles"),
        ("مصرة", "Mesra"), ("صيادة", "Sayada"),
        ("سيدي علي", "Sidi Ali"), ("خير الدين", "Kheir Eddine"),
        ("صوافلية", "Souaflia"), ("حاسي ماماش", "Hassi Mameche"),
        ("المظهرة", "Mazagran"), ("عشعاشة", "Achaacha"),
        ("سيدي لخضر", "Sidi Lakhdar"), ("أولاد بوغالم", "Ouled Boughalem"),
        ("أبو الحسن", "Abou El Hassan"),
    ]),
    (28, [  # M'Sila
        ("المسيلة", "M'Sila"), ("عين الملح", "Aïn El Melh"),
        ("بوسعادة", "Bou Saâda"), ("مقرة", "Magra"),
        ("سيدي عيسى", "Sidi Aïssa"), ("حمام الضلعة", "Hammam Dalaa"),
        ("المعاضيد", "Maâdid"), ("بن سرور", "Ben Srour"),
        ("مجانة", "Medjedel"), ("أولاد ماضي", "Ouled Madi"),
        ("عين الخضراء", "Aïn Khadra"), ("سلم النبضة", "Salmana"),
        ("وانوغة", "Ouanougha"),
    ]),
    (29, [  # Mascara
        ("معسكر", "Mascara"), ("تيغنيف", "Tighennif"),
        ("محمدية", "Mohammadia"), ("سيق", "Sig"),
        ("وادي العبطال", "Oued El Abtal"), ("حاسين", "Hacine"),
        ("أوجاج", "Oggaz"), ("غريس", "Ghris"),
        ("بوهني", "Bouhanifia"), ("المقطع", "El Keurt"),
        ("قوطيني", "Ghriss"), ("سيدي قادة", "Sidi Kada"),
        ("تيزي", "Tizi"), ("سانق", "Saïk"),
    ]),
    (30, [  # Ouargla
        ("ورقلة", "Ouargla"), ("حاسي مسعود", "Hassi Messaoud"),
        ("ن'قوسة", "N'Goussa"), ("روسيسات", "Rouissat"),
        ("عين البيضاء", "Ain El Beïda"), ("سيدي خويلد", "Sidi Khouiled"),
        ("تقرت", "Tebesbest"), ("منقر", "Mnegueur"),
        ("حاسي بن عبدالله", "Hassi Ben Abdallah"),
    ]),
    (31, [  # Oran
        ("وهران", "Oran"), ("عين البيا", "Aïn El Bya"),
        ("عين الترك", "Aïn El Turck"), ("بئر الجير", "Bir El Djir"),
        ("السانية", "Es Sénia"), ("قديل", "Gdyel"),
        ("حاسي بونيف", "Hassi Bounif"), ("مرسى الحجاج", "Mersa El Hadjadj"),
        ("القرمة", "El Kerma"), ("وادي تليلات", "Oued Tlelat"),
        ("بطيوة", "Boutlelis"), ("طفراوي", "Tafraoui"),
        ("مرسى الكبير", "Mers El Kébir"), ("سيدي الشحمي", "Sidi Chahmi"),
        ("بن فريحة", "Ben Freha"),
    ]),
    (32, [  # El Bayadh
        ("البيض", "El Bayadh"), ("برزينة", "Brezina"),
        ("بوعلام", "Boualem"), ("العبيد سيدي الشيخ", "El Abiodh Sidi Cheikh"),
        ("عين العراك", "Aïn El Orak"), ("غاسول", "Ghassoul"),
        ("سيدي عامر", "Sidi Ameur"), ("المهيرة", "El Mehara"),
        ("الرقيبة", "Rogassa"), ("كراكدة", "Kraakda"),
    ]),
    (33, [  # Illizi
        ("إليزي", "Illizi"), ("عين أمناس", "In Aménas"),
        ("برج عمر إدريس", "Bordj Omar Driss"),
    ]),
    (34, [  # Bordj Bou Arréridj
        ("برج بوعريريج", "Bordj Bou Arréridj"), ("عين تاغروت", "Aïn Taghrout"),
        ("العشير", "El Achir"), ("منصورة", "Mansoura"),
        ("رأس الواد", "Ras El Oued"), ("برج الغدير", "Bordj Ghedir"),
        ("مجانة", "Medjana"), ("حسناوة", "Hasnaoua"),
        ("أولاد دحمان", "Ouled Dahmane"), ("الميهرة", "El Mehir"),
        ("القصور", "El Ksour"), ("تيليلان", "Tixter"),
    ]),
    (35, [  # Boumerdès
        ("بومرداس", "Boumerdès"), ("خميس الخشنة", "Khemis El Khechna"),
        ("بودواو", "Boudouaou"), ("دلس", "Dellys"),
        ("ناصرية", "Naciria"), ("ثنية الحد", "Thénia"),
        ("تجلابين", "Tidjelabine"), ("عيسر", "Isser"),
        ("زموري", "Zemmouri"), ("برج منايل", "Bordj Menaïel"),
        ("بودواو الباحص", "Boudouaou El Bahes"), ("عميرة عرايس", "Amira Arres"),
        ("لقاطة", "Laqata"), ("سيدي داود", "Sidi Daoud"),
        ("الأربعاء أيت إيدير", "Ouled Moussa"),
    ]),
    (36, [  # El Tarf
        ("الطارف", "El Tarf"), ("عين الأسل", "Aïn El Assel"),
        ("بن مهيدي", "Ben Mehidi"), ("بسباس", "Besbes"),
        ("بوتلجة", "Bouteldja"), ("شعبة موخطار", "Chebaïta Mokhtar"),
        ("رمل السوق", "Ramel Souk"), ("الشط", "El Chatt"),
        ("درعان", "Dréan"), ("عين الكرمة", "Aïn Kerma"),
        ("بوحجار", "Bouhadjar"), ("الزيتونة", "El Zaytoun"),
    ]),
    (37, [  # Tindouf
        ("تندوف", "Tindouf"), ("أم العسل", "Oum El Assel"),
    ]),
    (38, [  # Tissemsilt
        ("تيسمسيلت", "Tissemsilt"), ("برج الأمير عبد القادر", "Bordj Emir Abdelkader"),
        ("لزهارية", "Lazharia"), ("ثنية الحد", "Theniet El Had"),
        ("عين كرمس", "Aïn Kermès"), ("لردجام", "Lardjem"),
        ("بويوسف بن علي", "Bouyounes"), ("خميستي", "Khemisti"),
        ("مديونة", "Melaab"),
    ]),
    (39, [  # El Oued
        ("الوادي", "El Oued"), ("قمار", "Guemar"),
        ("كويينين", "Kouinine"), ("الرباح", "Robbah"),
        ("رقيبة", "Reguiba"), ("البياضة", "Bayadha"),
        ("حسانى عبد الكريم", "Hassani Abdelkrim"), ("دبيلة", "Debila"),
        ("وادي العلندة", "Oued El Alenda"), ("النخلة", "Nakhla"),
        ("الطالب العربي", "Taleb Larbi"), ("ورماس", "Ourmas"),
        ("تغزوت", "Trifaoui"), ("سيدي عون", "Sidi Aoun"),
        ("المغير", "El Mghair"),
    ]),
    (40, [  # Khenchela
        ("خنشلة", "Khenchela"), ("عين توياة", "Aïn Touila"),
        ("باوي باغاي", "Babar"), ("شيليا", "Chelia"),
        ("قايس", "Kais"), ("الحامة", "El Hamma"),
        ("باغاي", "Baghaï"), ("المحمل", "El Mahmel"),
        ("مصارة", "Msara"),
    ]),
    (41, [  # Souk Ahras
        ("سوق أهراس", "Souk Ahras"), ("عين سلطان", "Aïn Soltane"),
        ("مشروحة", "Mechroha"), ("سدراتة", "Sedrata"),
        ("تاورة", "Taoura"), ("حددة", "Heddada"),
        ("أولاد إدريس", "Ouled Driss"), ("المشروحة", "Bir Bouhouche"),
        ("الزعرورية", "Terraguelt"), ("عين الزانة", "Aïn Zana"),
        ("ويلان", "Ouillène"),
    ]),
    (42, [  # Tipaza
        ("تيبازة", "Tipaza"), ("عين طاقورايت", "Aïn Tagourait"),
        ("بواسماعيل", "Bou Ismaïl"), ("شرشال", "Cherchell"),
        ("دامو", "Damous"), ("حجوط", "Hadjout"),
        ("قليعة", "Koléa"), ("سيدي غيلاس", "Sidi Ghilès"),
        ("قورايا", "Gouraya"), ("فوكة", "Fouka"),
        ("بئر توتة", "Bou Haroun"), ("أحمر العين", "Ahmer El Aïn"),
        ("مناصر", "Menaceur"), ("حمر الونزة", "Hadjeret Ennous"),
        ("أقفادو", "Aghbal"),
    ]),
    (43, [  # Mila
        ("ميلة", "Mila"), ("عين البيضاء أحريش", "Aïn Beïda Harriche"),
        ("شلغوم العيد", "Chelghoum Laïd"), ("فرجيوة", "Ferdjioua"),
        ("قرارم قوقة", "Grarem Gouga"), ("وادي عثمانية", "Oued Athmania"),
        ("تسادان هادة", "Tassadane Haddada"), ("المشريف", "El Méchrif"),
        ("السوقر", "Oued Seguen"), ("سيدي مروان", "Sidi Merouane"),
        ("تلاغمة", "Teleghma"), ("أولاد خلوف", "Ouled Khellouf"),
        ("ترعة", "Terrai Baïnen"),
    ]),
    (44, [  # Aïn Defla
        ("عين الدفلى", "Aïn Defla"), ("عين الشيخ", "Aïn Lechiekh"),
        ("بومدفع", "Boumedfaa"), ("العبادية", "El Abadia"),
        ("العطاف", "El Attaf"), ("حمام ريغة", "Hammam Righa"),
        ("خميس مليانة", "Khemis Miliana"), ("مليانة", "Miliana"),
        ("جليدة", "Djelida"), ("برج الأمير خالد", "Bordj Emir Khaled"),
        ("الجمعة أولاد شيخ", "Djemaa Ouled Cheikh"), ("بربر", "Bir Ouled Khelil"),
        ("عين لحجر", "Aïn Torki"), ("روينة", "Rouina"),
    ]),
    (45, [  # Naâma
        ("النعامة", "Naâma"), ("عين الصفراء", "Aïn Sefra"),
        ("مشرع الصفا", "Méchraa Sfa"), ("سفيسيفة", "Sfissifa"),
        ("تيوت", "Tiout"), ("عين بن خليل", "Aïn Ben Khelil"),
        ("مغرار", "Moghrar"), ("كراكو", "Krakou"),
    ]),
    (46, [  # Aïn Témouchent
        ("عين تموشنت", "Aïn Témouchent"), ("عين كيحال", "Aïn Kihal"),
        ("عين الربا", "Aïn El Arba"), ("بني صاف", "Béni Saf"),
        ("المالح", "El Malah"), ("حمام بوحجر", "Hammam Bou Hadjar"),
        ("أولاد كيحال", "Ouled Kihal"), ("شعبة الهم", "Chaâbet El Ham"),
        ("أوقاس", "Aghlal"), ("ترغة", "Terga"),
        ("سيدي بن عدة", "Sidi Ben Adda"), ("سيدي سافي", "Sidi Safi"),
    ]),
    (47, [  # Ghardaïa
        ("غرداية", "Ghardaïa"), ("بريان", "Berriane"),
        ("العطف", "El Atteuf"), ("قرارة", "Guerrara"),
        ("متليلي", "Metlili"), ("بونورة", "Bounoura"),
        ("ضاية بن دحوة", "Daya Ben Dahoua"), ("زلفانة", "Zelfana"),
    ]),
    (48, [  # Relizane
        ("غليزان", "Relizane"), ("عين تارق", "Aïn Tarek"),
        ("مازونة", "Mazouna"), ("وادي الرهيو", "Oued Rhiou"),
        ("يلل", "Yellel"), ("بنيان", "Beniane"),
        ("مرجة سيدي عابد", "Merdja Sidi Abed"), ("جديوية", "Djidiouia"),
        ("سيدي سعادة", "Sidi Saada"), ("منتاق الرحمانية", "Ramka"),
        ("بلعسل", "Belassel Bouzegza"),
    ]),
    (49, [  # El M'Ghair
        ("المغير", "El M'Ghair"), ("جامعة", "Djamaa"),
        ("سيدي عمران", "Sidi Amrane"), ("ستيل", "Still"),
        ("أم طيور", "Oum Touyour"), ("حاسي خليفة", "Hassi Khalifa"),
        ("مرارة", "Merrara"),
    ]),
    (50, [  # El Meniaa
        ("المنيعة", "El Meniaa"), ("حاسي القارة", "Hassi Gara"),
        ("يسف", "Issouf"), ("حاسي الفحل", "Hassi El Féhal"),
    ]),
    (51, [  # Ouled Djellal
        ("أولاد جلال", "Ouled Djellal"), ("الدوسن", "Doucen"),
        ("سيدي خالد", "Sidi Khaled"), ("رأس الميعاد", "Ras El Miaa"),
    ]),
    (52, [  # Bordj Baji Mokhtar
        ("برج باجي مختار", "Bordj Baji Mokhtar"), ("تيميؤين", "Timiaouine"),
    ]),
    (53, [  # Béni Abbès
        ("بني عباس", "Béni Abbès"), ("العواطة", "El Ouata"),
        ("كرزاز", "Kerzaz"), ("تابلبالة", "Tabelbala"),
        ("بني يخلف", "Beni Ikhlef"), ("أولاد خضير", "Ouled Khodeir"),
    ]),
    (54, [  # Timimoun
        ("تيميمون", "Timimoun"), ("أوقروت", "Aougrout"),
        ("شاروين", "Charouine"), ("دلدول", "Deldoul"),
        ("أولاد سعيد", "Ouled Saïd"), ("تينركوك", "Tinerkouk"),
        ("قصر قدور", "Ksar Kaddour"),
    ]),
    (55, [  # Touggourt
        ("تقرت", "Touggourt"), ("تماسين", "Témacine"),
        ("الحاجرة", "El Hadjira"), ("بليدة أومر", "Blidet Amor"),
        ("نزلة", "Nezla"), ("الزاوية العابدية", "Zaouia El Abidia"),
        ("مقارين", "Megarine"),
    ]),
    (56, [  # Djanet
        ("جانت", "Djanet"), ("برج الهواس", "Bordj El Haouès"),
    ]),
    (57, [  # In Salah
        ("عين صالح", "In Salah"), ("فقارة الزوة", "Foggaret Ezzoua"),
        ("عين قار", "In Ghar"),
    ]),
    (58, [  # In Guezzam
        ("عين قزام", "In Guezzam"), ("تين زواتين", "Tin Zaouatine"),
    ]),
]


def populate_baladias(apps, schema_editor):
    Wilaya = apps.get_model("shop", "Wilaya")
    Baladia = apps.get_model("shop", "Baladia")

    wilaya_map = {w.code: w for w in Wilaya.objects.all()}
    to_create = []
    for code, baladias in BALADIAS:
        wilaya = wilaya_map.get(code)
        if not wilaya:
            continue
        for name_ar, name_fr in baladias:
            to_create.append(
                Baladia(wilaya=wilaya, name_ar=name_ar, name_fr=name_fr, is_active=True)
            )
    Baladia.objects.bulk_create(to_create)


def depopulate_baladias(apps, schema_editor):
    apps.get_model("shop", "Baladia").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_baladia"),
    ]

    operations = [
        migrations.RunPython(populate_baladias, depopulate_baladias),
    ]
