# Generated by Django 5.2.15 on 2026-06-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_wilaya_zr_fields_baladia_zr_territory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('', 'لا يوجد'), ('new', 'جديد'), ('sale', 'تخفيض'), ('limited', 'محدود'), ('bestseller', 'الأكثر مبيعًا')], default='', max_length=20, verbose_name='الشارة'),
        ),
    ]
