# Generated by Django 5.2.15 on 2026-06-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_topbar', models.CharField(help_text='Top announcement bar shown on every page.', max_length=255)),
                ('home_nav_logo_tagline', models.CharField(blank=True, help_text="Small line under the logo in the nav (e.g. 'Heritage Atelier · Since 1994').", max_length=100)),
                ('home_hero_eyebrow', models.CharField(max_length=150)),
                ('home_hero_title_line1', models.CharField(help_text='First line of the hero <h1> (plain text).', max_length=150)),
                ('home_hero_title_emphasis', models.CharField(help_text='Middle word/phrase of the hero <h1>, rendered in <em>.', max_length=150)),
                ('home_hero_title_line3', models.CharField(help_text='Third line of the hero <h1> (plain text).', max_length=150)),
                ('home_hero_subtitle', models.TextField()),
                ('about_hero_title_main', models.CharField(help_text="Plain part of the page <h1>, e.g. 'Our'.", max_length=150)),
                ('about_hero_title_emphasis', models.CharField(help_text="Emphasized part of the page <h1>, rendered in <em>, e.g. 'Story'.", max_length=150)),
                ('about_hero_subtitle', models.TextField()),
                ('about_story_title_main', models.CharField(max_length=200)),
                ('about_story_title_emphasis', models.CharField(max_length=200)),
                ('about_story_paragraph_1', models.TextField()),
                ('about_story_paragraph_2', models.TextField()),
                ('contact_hero_title_main', models.CharField(max_length=150)),
                ('contact_hero_title_emphasis', models.CharField(max_length=150)),
                ('contact_hero_subtitle', models.TextField()),
                ('contact_intro_title_main', models.CharField(max_length=200)),
                ('contact_intro_title_emphasis', models.CharField(max_length=200)),
                ('contact_intro_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Front Settings',
                'verbose_name_plural': 'Front Settings',
            },
        ),
    ]
