# Generated by Django 6.0.6 on 2026-06-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bilingual_front_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustStrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='Icon class name, emoji, or SVG key used by the frontend.', max_length=100)),
                ('label_ar', models.CharField(max_length=120)),
                ('label_en', models.CharField(blank=True, max_length=120)),
                ('description_ar', models.CharField(blank=True, max_length=255)),
                ('description_en', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trust Strip',
                'verbose_name_plural': 'Trust Strips',
                'ordering': ('sort_order',),
            },
        ),
    ]
