# Generated by Django 5.2.15 on 2026-06-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_truststrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_email', models.EmailField(blank=True, default='', help_text='Primary store email.', max_length=254)),
                ('store_phone', models.CharField(blank=True, default='', help_text='Primary store phone.', max_length=30)),
                ('store_whatsapp', models.CharField(blank=True, default='', help_text='WhatsApp number (digits only for wa.me link).', max_length=30)),
                ('store_hours_ar', models.CharField(blank=True, default='', help_text='Working hours (Arabic).', max_length=200)),
                ('store_hours_en', models.CharField(blank=True, help_text='Working hours (English).', max_length=200)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL.')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL.')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn page URL.')),
                ('whatsapp_url', models.URLField(blank=True, help_text='WhatsApp direct chat URL (e.g. https://wa.me/213555...).')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.AddField(
            model_name='frontsettings',
            name='about_stat_1_label_ar',
            field=models.CharField(default='', help_text='Stat 1 label (Arabic).', max_length=100),
        ),
        migrations.AddField(
            model_name='frontsettings',
            name='about_stat_1_label_en',
            field=models.CharField(blank=True, help_text='Stat 1 label (English).', max_length=100),
        ),
        migrations.AddField(
            model_name='frontsettings',
            name='about_stat_1_value',
            field=models.CharField(default='30+', help_text="Stat 1 value, e.g. '30+'.", max_length=20),
        ),
        migrations.AddField(
            model_name='frontsettings',
            name='about_stat_2_label_ar',
            field=models.CharField(default='', help_text='Stat 2 label (Arabic).', max_length=100),
        ),
        migrations.AddField(
            model_name='frontsettings',
            name='about_stat_2_label_en',
            field=models.CharField(blank=True, help_text='Stat 2 label (English).', max_length=100),
        ),
        migrations.AddField(
            model_name='frontsettings',
            name='about_stat_2_value',
            field=models.CharField(default='6', help_text='Stat 2 value.', max_length=20),
        ),
        migrations.AddField(
            model_name='frontsettings',
            name='about_stat_3_label_ar',
            field=models.CharField(default='', help_text='Stat 3 label (Arabic).', max_length=100),
        ),
        migrations.AddField(
            model_name='frontsettings',
            name='about_stat_3_label_en',
            field=models.CharField(blank=True, help_text='Stat 3 label (English).', max_length=100),
        ),
        migrations.AddField(
            model_name='frontsettings',
            name='about_stat_3_value',
            field=models.CharField(default='48', help_text='Stat 3 value.', max_length=20),
        ),
        migrations.AddField(
            model_name='frontsettings',
            name='about_stat_4_label_ar',
            field=models.CharField(default='', help_text='Stat 4 label (Arabic).', max_length=100),
        ),
        migrations.AddField(
            model_name='frontsettings',
            name='about_stat_4_label_en',
            field=models.CharField(blank=True, help_text='Stat 4 label (English).', max_length=100),
        ),
        migrations.AddField(
            model_name='frontsettings',
            name='about_stat_4_value',
            field=models.CharField(default='4k+', help_text='Stat 4 value.', max_length=20),
        ),
        migrations.AddField(
            model_name='frontsettings',
            name='about_story_paragraph_3_ar',
            field=models.TextField(default='', help_text='About story, third paragraph (Arabic).'),
        ),
        migrations.AddField(
            model_name='frontsettings',
            name='about_story_paragraph_3_en',
            field=models.TextField(blank=True, help_text='About story, third paragraph (English, optional).'),
        ),
    ]
