# Generated by Django 5.2.15 on 2026-06-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_frontsettings_intro_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontsettings',
            name='about_intro_eyebrow_ar',
            field=models.CharField(blank=True, help_text="About intro eyebrow text (Arabic), e.g. 'التزامنا'.", max_length=150),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_intro_title_ar',
            field=models.CharField(blank=True, help_text='About intro section title (Arabic). Use {{em}}…{{/em}} for emphasis.', max_length=255),
        ),
    ]
