# Generated by Django 5.2.15 on 2026-06-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_english_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontsettings',
            name='about_hero_title_emphasis_ar',
            field=models.CharField(default='', help_text='Emphasized part of the page <h1>, rendered in <em> (Arabic).', max_length=150),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_hero_title_main_ar',
            field=models.CharField(default='', help_text='Plain part of the page <h1> (Arabic).', max_length=150),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_intro_eyebrow_ar',
            field=models.CharField(blank=True, help_text='About intro eyebrow text (Arabic).', max_length=150),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='home_hero_title_line1_ar',
            field=models.CharField(default='', help_text='First line of the hero <h1> (Arabic).', max_length=150),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='home_hero_title_line3_ar',
            field=models.CharField(default='', help_text='Third line of the hero <h1> (Arabic).', max_length=150),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='home_nav_logo_tagline_ar',
            field=models.CharField(blank=True, help_text='Small line under the logo in the nav (Arabic).', max_length=100),
        ),
    ]
