# Generated by Django 5.2.15 on 2026-06-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_frontsettings_about_hero_title_emphasis_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'معلومات التواصل', 'verbose_name_plural': 'معلومات التواصل'},
        ),
        migrations.AlterModelOptions(
            name='frontsettings',
            options={'verbose_name': 'إعدادات الواجهة', 'verbose_name_plural': 'إعدادات الواجهة'},
        ),
        migrations.AlterModelOptions(
            name='truststrip',
            options={'ordering': ('sort_order',), 'verbose_name': 'شريط الثقة', 'verbose_name_plural': 'أشرطة الثقة'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL.', verbose_name='رابط فيسبوك'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL.', verbose_name='رابط إنستغرام'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn page URL.', verbose_name='رابط لينكدإن'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='store_email',
            field=models.EmailField(blank=True, default='', help_text='Primary store email.', max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='store_hours_ar',
            field=models.CharField(blank=True, default='', help_text='Working hours (Arabic).', max_length=200, verbose_name='ساعات العمل'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='store_phone',
            field=models.CharField(blank=True, default='', help_text='Primary store phone.', max_length=30, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='store_whatsapp',
            field=models.CharField(blank=True, default='', help_text='WhatsApp number (digits only for wa.me link).', max_length=30, verbose_name='رقم واتساب'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='WhatsApp direct chat URL (e.g. https://wa.me/213555...).', verbose_name='رابط واتساب'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_hero_subtitle_ar',
            field=models.TextField(default='', help_text='About hero subtitle (Arabic).', verbose_name='وصف بطل من نحن'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_hero_title_emphasis_ar',
            field=models.CharField(default='', help_text='Emphasized part of the page <h1>, rendered in <em> (Arabic).', max_length=150, verbose_name='عنوان صفحة من نحن – الجزء المميز'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_hero_title_main_ar',
            field=models.CharField(default='', help_text='Plain part of the page <h1> (Arabic).', max_length=150, verbose_name='عنوان صفحة من نحن – الجزء العادي'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_intro_eyebrow_ar',
            field=models.CharField(blank=True, help_text='About intro eyebrow text (Arabic).', max_length=150, verbose_name='نص فوق عنوان مقدمة من نحن'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_intro_text_ar',
            field=models.TextField(blank=True, help_text='About intro paragraph (Arabic).', verbose_name='نص مقدمة من نحن'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_intro_title_ar',
            field=models.CharField(blank=True, help_text='About intro section title (Arabic). Use {{em}}…{{/em}} for emphasis.', max_length=255, verbose_name='عنوان مقدمة من نحن'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_stat_1_label_ar',
            field=models.CharField(default='', help_text='Stat 1 label (Arabic).', max_length=100, verbose_name='تسمية الإحصاء 1'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_stat_1_value',
            field=models.CharField(default='30+', help_text="Stat 1 value, e.g. '30+'.", max_length=20, verbose_name='قيمة الإحصاء 1'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_stat_2_label_ar',
            field=models.CharField(default='', help_text='Stat 2 label (Arabic).', max_length=100, verbose_name='تسمية الإحصاء 2'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_stat_2_value',
            field=models.CharField(default='6', help_text='Stat 2 value.', max_length=20, verbose_name='قيمة الإحصاء 2'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_stat_3_label_ar',
            field=models.CharField(default='', help_text='Stat 3 label (Arabic).', max_length=100, verbose_name='تسمية الإحصاء 3'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_stat_3_value',
            field=models.CharField(default='48', help_text='Stat 3 value.', max_length=20, verbose_name='قيمة الإحصاء 3'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_stat_4_label_ar',
            field=models.CharField(default='', help_text='Stat 4 label (Arabic).', max_length=100, verbose_name='تسمية الإحصاء 4'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_stat_4_value',
            field=models.CharField(default='4k+', help_text='Stat 4 value.', max_length=20, verbose_name='قيمة الإحصاء 4'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_story_image',
            field=models.ImageField(blank=True, help_text='Upload story section image (takes priority over the URL field below).', upload_to='story/', verbose_name='صورة القصة'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_story_image_label_ar',
            field=models.CharField(blank=True, help_text='Image caption shown below the photo (Arabic).', max_length=200, verbose_name='تعليق الصورة'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_story_image_url',
            field=models.URLField(blank=True, help_text='Or paste a direct image URL (used if no uploaded image is set).', verbose_name='رابط صورة القصة'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_story_paragraph_1_ar',
            field=models.TextField(default='', help_text='About story, first paragraph (Arabic).', verbose_name='فقرة القصة 1'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_story_paragraph_2_ar',
            field=models.TextField(default='', help_text='About story, second paragraph (Arabic).', verbose_name='فقرة القصة 2'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_story_paragraph_3_ar',
            field=models.TextField(default='', help_text='About story, third paragraph (Arabic).', verbose_name='فقرة القصة 3'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_story_title_emphasis_ar',
            field=models.CharField(default='', help_text='About story title, emphasized part (Arabic).', max_length=200, verbose_name='عنوان القصة – الجزء المميز'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='about_story_title_main_ar',
            field=models.CharField(default='', help_text='About story title, plain part (Arabic).', max_length=200, verbose_name='عنوان القصة – الجزء العادي'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='contact_hero_subtitle_ar',
            field=models.TextField(default='', help_text='Contact hero subtitle (Arabic).', verbose_name='وصف بطل التواصل'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='contact_hero_title_emphasis_ar',
            field=models.CharField(default='', help_text='Contact hero title, emphasized part (Arabic).', max_length=150, verbose_name='عنوان بطل التواصل – الجزء المميز'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='contact_hero_title_main_ar',
            field=models.CharField(default='', help_text='Contact hero title, plain part (Arabic).', max_length=150, verbose_name='عنوان بطل التواصل – الجزء العادي'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='contact_intro_text_ar',
            field=models.TextField(default='', help_text='Contact intro statement (Arabic).', verbose_name='نص مقدمة التواصل'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='contact_intro_title_emphasis_ar',
            field=models.CharField(default='', help_text='Contact intro title, emphasized part (Arabic).', max_length=200, verbose_name='عنوان مقدمة التواصل – الجزء المميز'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='contact_intro_title_main_ar',
            field=models.CharField(default='', help_text='Contact intro title, plain part (Arabic).', max_length=200, verbose_name='عنوان مقدمة التواصل – الجزء العادي'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='home_hero_eyebrow_ar',
            field=models.CharField(default='', help_text='Hero eyebrow text (Arabic).', max_length=150, verbose_name='نص فوق العنوان (الرئيسية)'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='home_hero_subtitle_ar',
            field=models.TextField(default='', help_text='Hero subtitle (Arabic).', verbose_name='وصف البطل (الرئيسية)'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='home_hero_title_emphasis_ar',
            field=models.CharField(default='', help_text='Middle word/phrase of the hero <h1>, rendered in <em> (Arabic).', max_length=150, verbose_name='عنوان البطل – الجزء المميز'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='home_hero_title_line1_ar',
            field=models.CharField(default='', help_text='First line of the hero <h1> (Arabic).', max_length=150, verbose_name='عنوان البطل – السطر الأول'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='home_hero_title_line3_ar',
            field=models.CharField(default='', help_text='Third line of the hero <h1> (Arabic).', max_length=150, verbose_name='عنوان البطل – السطر الثالث'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='home_nav_logo_tagline_ar',
            field=models.CharField(blank=True, help_text='Small line under the logo in the nav (Arabic).', max_length=100, verbose_name='شعار التنقل الفرعي'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='home_topbar_ar',
            field=models.CharField(default='', help_text='Top announcement bar shown on every page (Arabic).', max_length=255, verbose_name='شريط الإعلان العلوي'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='product_shipping_algeria_ar',
            field=models.CharField(blank=True, help_text='Algeria delivery line shown as bullet (Arabic).', max_length=255, verbose_name='خط التوصيل – الجزائر'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='product_shipping_france_ar',
            field=models.CharField(blank=True, help_text='France & Europe delivery line shown as bullet (Arabic).', max_length=255, verbose_name='خط التوصيل – فرنسا وأوروبا'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='product_shipping_intro_ar',
            field=models.TextField(blank=True, help_text='Shipping tab intro paragraph (Arabic).', verbose_name='مقدمة تبويب الشحن'),
        ),
        migrations.AlterField(
            model_name='frontsettings',
            name='product_shipping_tracking_ar',
            field=models.CharField(blank=True, help_text='Tracking & insurance line shown as bullet (Arabic).', max_length=255, verbose_name='خط التتبع والتأمين'),
        ),
        migrations.AlterField(
            model_name='truststrip',
            name='description_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='truststrip',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class name, emoji, or SVG key used by the frontend.', max_length=100, verbose_name='الأيقونة'),
        ),
        migrations.AlterField(
            model_name='truststrip',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='truststrip',
            name='label_ar',
            field=models.CharField(max_length=120, verbose_name='التسمية'),
        ),
        migrations.AlterField(
            model_name='truststrip',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
    ]
