"""
Management command: python manage.py seed_products

Seeds the database with heritage products shown in the frontend ShopPage.
Safe to run multiple times — skips products that already exist by SKU.
"""

from django.core.management.base import BaseCommand

from apps.shop.models import Category, Product

# ---------------------------------------------------------------------------
# Original 9 heritage adult products
# ---------------------------------------------------------------------------
PRODUCTS = [
    {
        "name_ar": "البرنوس العاجي الكبير",
        "name": "Grand Ivory Burnous",
        "sku": "BB-TLE-001-IV",
        "origin": "Tlemcen · Pure Wool",
        "material": "100% Pure Wool",
        "price": 12500,
        "old_price": None,
        "badge": "new",
        "is_new": True,
        "short_description_ar": "برنوس فاخر منسوج من أجود أصواف تلمسان، يتميز بتطريز يدوي وسقوط تراثي يُفضَّل للأعراس والمناسبات.",
        "short_description": "A prestige burnous woven from the finest Tlemcen wool, featuring hand-stitched trim and a heritage drape favoured for weddings and celebrations.",
        "description_ar": "برنوس فاخر منسوج من أجود أصواف تلمسان، يتميز بتطريز يدوي وسقوط تراثي يُفضَّل للأعراس والمناسبات. البرنوس هو الرداء الأصيل للمغرب — وقار ودفء وحضور لا يُضاهى.",
        "description": "A prestige burnous woven from the finest Tlemcen wool, featuring hand-stitched trim and a heritage drape favoured for weddings and celebrations.",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80",
        "rating": "4.90",
        "review_count": 24,
        "stock_quantity": 50,
        "category_name": "Burnous",
        "category_name_ar": "البرنوس",
    },
    {
        "name_ar": "قفطان قسنطينة الحريري",
        "name": "Constantine Silk Kaftan",
        "sku": "BB-CON-002-SK",
        "origin": "Constantine · Pure Silk",
        "material": "Pure Silk",
        "price": 19800,
        "old_price": 24000,
        "badge": "sale",
        "is_new": False,
        "short_description_ar": "مطرز يدوياً بخيوط ذهبية على الطراز القسنطيني. يأتي مع حزام مطابق.",
        "short_description": "Hand-embroidered with gold-thread motifs in the traditional Qasrantina style. Supplied with a matching sash belt.",
        "description_ar": "مطرز يدوياً بخيوط ذهبية على الطراز القسنطيني التقليدي. يأتي مع حزام مطابق.",
        "description": "Hand-embroidered with gold-thread motifs in the traditional Qasrantina style. Supplied with a matching sash belt.",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500&q=80",
        "rating": "4.80",
        "review_count": 37,
        "stock_quantity": 20,
        "category_name": "Kaftans",
        "category_name_ar": "القفاطين",
    },
    {
        "name_ar": "طقم الشاشية والتاقلموست",
        "name": "Chechia & Tagelmust Set",
        "sku": "BB-KAB-003-CT",
        "origin": "Kabylie · Handloomed Wool",
        "material": "Handloomed Wool",
        "price": 3200,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "طقم غطاء الرأس الكامل — شاشية حمراء وتاقلموست نيلية — من نسج قبائل كاباي.",
        "short_description": "A complete headwear set — red felt chechia and indigo tagelmust — crafted by Kabyle weavers using looms unchanged for centuries.",
        "description_ar": "طقم غطاء الرأس الكامل — شاشية حمراء وتاقلموست نيلية — من نسج حرفيي القبائل بأنوال لم تتغير منذ قرون.",
        "description": "A complete headwear set — red felt chechia and indigo tagelmust — crafted by Kabyle weavers using looms unchanged for centuries.",
        "image_url": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&q=80",
        "rating": "4.00",
        "review_count": 15,
        "stock_quantity": 30,
        "category_name": "Accessories",
        "category_name_ar": "الإكسسوارات",
    },
    {
        "name_ar": "حزام الخدمي المزخرف",
        "name": "Ornate Khodmi Belt",
        "sku": "BB-ANN-013-BELT",
        "origin": "Annaba · Silver-thread craft",
        "material": "Silver thread on velvet",
        "price": 8900,
        "old_price": None,
        "badge": "limited",
        "is_new": False,
        "is_limited": True,
        "short_description_ar": "حزام احتفالي فاخر بخيط فضي على قطيفة برغندي، مثبّت بإبزيم محفور. قطعة نادرة للمقتنين.",
        "short_description": "An elaborately worked ceremonial belt in silver thread on deep burgundy velvet, secured with an engraved clasp. A rare collector's piece.",
        "description_ar": "حزام احتفالي فاخر بخيط فضي على قطيفة برغندي عميق، مثبّت بإبزيم محفور. قطعة نادرة للمقتنين.",
        "description": "An elaborately worked ceremonial belt in silver thread on deep burgundy velvet, secured with an engraved clasp. A rare collector's piece.",
        "image_url": "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=500&q=80",
        "rating": "5.00",
        "review_count": 8,
        "stock_quantity": 5,
        "category_name": "Accessories",
        "category_name_ar": "الإكسسوارات",
    },
    {
        "name_ar": "بلاغ مطرز بالذهب",
        "name": "Gold-Stitched Babouches",
        "sku": "BB-ALG-005-BAB",
        "origin": "Algiers · Natural leather",
        "material": "Natural leather",
        "price": 4700,
        "old_price": None,
        "badge": "new",
        "is_new": True,
        "short_description_ar": "بلاغ جلدي ناعم بتطريز ذهبي يدوي على المقدمة والكعب. مريح طوال اليوم للمناسبات.",
        "short_description": "Soft leather babouches with hand-stitched gold embroidery across the toe and heel. Comfortable for all-day ceremonial wear.",
        "description_ar": "بلاغ جلدي ناعم بتطريز ذهبي يدوي على المقدمة والكعب. مريح طوال اليوم للمناسبات الرسمية.",
        "description": "Soft leather babouches with hand-stitched gold embroidery across the toe and heel. Comfortable for all-day ceremonial wear.",
        "image_url": "https://images.unsplash.com/photo-1600074169098-16a54d791d0d?w=500&q=80",
        "rating": "4.00",
        "review_count": 19,
        "stock_quantity": 40,
        "category_name": "Footwear",
        "category_name_ar": "الأحذية",
    },
    {
        "name_ar": "الجلابية الليلية",
        "name": "Midnight Djellaba",
        "sku": "BB-TLE-006-DJ",
        "origin": "Tlemcen · Wool-cotton blend",
        "material": "Wool-cotton blend",
        "price": 9400,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "جلابية كحلية اللون بزرار مضفر يدوي وزخرفة هندسية خفية على الأكمام والياقة.",
        "short_description": "A deep navy djellaba with hand-braided closure toggles and discreet geometric trim at the cuffs and collar.",
        "description_ar": "جلابية كحلية اللون بزرار مضفر يدوي وزخرفة هندسية خفية على الأكمام والياقة.",
        "description": "A deep navy djellaba with hand-braided closure toggles and discreet geometric trim at the cuffs and collar.",
        "image_url": "https://images.unsplash.com/photo-1597466599360-3b596c3d7cb7?w=500&q=80",
        "rating": "5.00",
        "review_count": 31,
        "stock_quantity": 25,
        "category_name": "Djellabas",
        "category_name_ar": "الجلابيات",
    },
    {
        "name_ar": "طقم الشدة العروسية",
        "name": "Bridal Chedda Ensemble",
        "sku": "BB-CON-007-CHE",
        "origin": "Constantine · Velvet & silk",
        "material": "Velvet & silk",
        "price": 32500,
        "old_price": 38000,
        "badge": "sale",
        "is_new": False,
        "short_description_ar": "طقم شدة عروس كامل يشمل البوليرو المطرز والتنورة وزينة الرأس بالذهب القسنطيني التقليدي.",
        "short_description": "Full bridal chedda set including the embroidered bolero, skirt, and head ornaments in traditional Qasrantina gold-work.",
        "description_ar": "طقم شدة عروس كامل يشمل البوليرو المطرز والتنورة وزينة الرأس بالذهب القسنطيني.",
        "description": "Full bridal chedda set including the embroidered bolero, skirt, and head ornaments in traditional Qasrantina gold-work.",
        "image_url": "https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=500&q=80",
        "rating": "4.00",
        "review_count": 11,
        "stock_quantity": 10,
        "category_name": "Bridal",
        "category_name_ar": "الأعراس",
    },
    {
        "name_ar": "سجادة صلاة غرداوية",
        "name": "Ghardaïa Prayer Rug",
        "sku": "BB-GHA-008-RUG",
        "origin": "Ghardaïa · Hand-knotted wool",
        "material": "Hand-knotted wool",
        "price": 16200,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "سجادة صلاة موزابية بأنماط هندسية في صوف طبيعي غير مصبوغ، من نسج حرفيي غرداية.",
        "short_description": "A hand-knotted M'zab geometric prayer rug in natural undyed wool, crafted by Mozabite weavers in Ghardaïa.",
        "description_ar": "سجادة صلاة موزابية بأنماط هندسية في صوف طبيعي غير مصبوغ، من نسج حرفيي بني ميزاب في غرداية.",
        "description": "A hand-knotted M'zab geometric prayer rug in natural undyed wool, crafted by Mozabite weavers in Ghardaïa.",
        "image_url": "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&q=80",
        "rating": "5.00",
        "review_count": 6,
        "stock_quantity": 15,
        "category_name": "Home & Decor",
        "category_name_ar": "الديكور والمنزل",
    },
    {
        "name_ar": "الحايك المطرز",
        "name": "Embroidered Haik Wrap",
        "sku": "BB-ALG-009-HAI",
        "origin": "Algiers · Fine cotton",
        "material": "Fine cotton",
        "price": 5600,
        "old_price": None,
        "badge": "new",
        "is_new": True,
        "short_description_ar": "حايك مطرز بقطن ناعم أبيض مع حواف زهرية رقيقة، مثالي للمناسبات الرسمية.",
        "short_description": "An exquisitely embroidered haik in fine white cotton with delicate floral edging, perfect for formal occasions.",
        "description_ar": "حايك مطرز بقطن ناعم أبيض مع حواف زهرية رقيقة، مثالي للمناسبات الرسمية.",
        "description": "An exquisitely embroidered haik in fine white cotton with delicate floral edging, perfect for formal occasions.",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80",
        "rating": "5.00",
        "review_count": 22,
        "stock_quantity": 35,
        "category_name": "Accessories",
        "category_name_ar": "الإكسسوارات",
    },
]

# ---------------------------------------------------------------------------
# Traditional Algerian children's clothing — 21 products
# ---------------------------------------------------------------------------
CHILDREN_PRODUCTS = [
    # ── Girls (7) ──────────────────────────────────────────────────────────
    {
        "name_ar": "قندورة الكاراكو",
        "name": "Karakou Girl's Outfit",
        "sku": "CH-G-001-KRK",
        "origin": "Algiers · Velvet & embroidery",
        "material": "Velvet with gold embroidery",
        "price": 8500,
        "old_price": None,
        "badge": "new",
        "is_new": True,
        "short_description_ar": "لباس تقليدي مطرز بالذهب على القطيفة — الكاراكو الأصيل للبنات في المناسبات الكبرى.",
        "short_description": "Traditional embroidered velvet outfit — the authentic Karakou for girls on special occasions.",
        "description_ar": "الكاراكو قطعة تراثية جزائرية أصيلة، مطرزة يدوياً بخيوط ذهبية على قطيفة فاخرة. مثالي للأعراس والأعياد.",
        "description": "The Karakou is an authentic Algerian heritage piece, hand-embroidered with gold threads on luxurious velvet. Perfect for weddings and celebrations.",
        "image_url": "https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=500&q=80",
        "rating": "4.80",
        "review_count": 12,
        "stock_quantity": 20,
        "category_name": "Girls Traditional Clothing",
        "category_name_ar": "ملابس البنات التقليدية",
    },
    {
        "name_ar": "الشدة التلمسانية",
        "name": "Chedda Tlemcenia",
        "sku": "CH-G-002-CHT",
        "origin": "Tlemcen · Silk & brocade",
        "material": "Silk and brocade",
        "price": 12000,
        "old_price": 15000,
        "badge": "sale",
        "is_new": False,
        "short_description_ar": "لباس احتفالي تقليدي مستوحى من تراث تلمسان — للبنات في المناسبات.",
        "short_description": "Ceremonial traditional dress inspired by Tlemcen heritage — for girls on special occasions.",
        "description_ar": "الشدة التلمسانية من أرقى الألبسة التقليدية الجزائرية، تجمع بين فخامة الحرير وروعة التطريز.",
        "description": "The Chedda Tlemcenia is one of the finest Algerian traditional garments, combining silk luxury with exquisite embroidery.",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80",
        "rating": "4.90",
        "review_count": 18,
        "stock_quantity": 15,
        "category_name": "Girls Traditional Clothing",
        "category_name_ar": "ملابس البنات التقليدية",
    },
    {
        "name_ar": "البلوزة الوهرانية",
        "name": "Blouza Wahrania",
        "sku": "CH-G-003-BLW",
        "origin": "Oran · Embroidered fabric",
        "material": "Embroidered cotton-silk blend",
        "price": 7200,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "فستان أنيق من وهران بتطريز جميل — يعكس تراث المدينة الساحلية الجميلة.",
        "short_description": "Elegant dress from Oran with beautiful embroidery — reflecting the heritage of the beautiful coastal city.",
        "description_ar": "البلوزة الوهرانية لباس تقليدي أنيق يجمع بين الجمال والتراث الأصيل لمدينة وهران.",
        "description": "The Blouza Wahrania is an elegant traditional garment combining beauty and authentic heritage of the city of Oran.",
        "image_url": "https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=500&q=80",
        "rating": "4.60",
        "review_count": 9,
        "stock_quantity": 25,
        "category_name": "Girls Traditional Clothing",
        "category_name_ar": "ملابس البنات التقليدية",
    },
    {
        "name_ar": "القندورة",
        "name": "Gandoura Girl",
        "sku": "CH-G-004-GND",
        "origin": "Algeria · Embroidered cotton",
        "material": "Light embroidered cotton",
        "price": 4500,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "قندورة خفيفة مطرزة للبنات — راحة وأناقة في لباس واحد.",
        "short_description": "Light embroidered traditional dress for girls — comfort and elegance in one garment.",
        "description_ar": "القندورة لباس تقليدي كلاسيكي للبنات، خفيف ومريح مع تطريز يدوي جميل.",
        "description": "The Gandoura is a classic traditional dress for girls, light and comfortable with beautiful hand embroidery.",
        "image_url": "https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=500&q=80",
        "rating": "4.40",
        "review_count": 22,
        "stock_quantity": 40,
        "category_name": "Girls Traditional Clothing",
        "category_name_ar": "ملابس البنات التقليدية",
    },
    {
        "name_ar": "الجبة الفرقانية",
        "name": "Djebba Fergani",
        "sku": "CH-G-005-DJF",
        "origin": "Constantine · Traditional fabric",
        "material": "Traditional woven fabric",
        "price": 6800,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "لباس تقليدي قسنطيني أصيل للبنات — يحمل روح مدينة الجسور المعلقة.",
        "short_description": "Traditional outfit from Constantine for girls — carrying the spirit of the City of Suspended Bridges.",
        "description_ar": "الجبة الفرقانية من تراث قسنطينة العريق، تتميز بتطريز دقيق وألوان زاهية تعكس ثقافة المنطقة.",
        "description": "The Djebba Fergani from the ancient heritage of Constantine, featuring delicate embroidery and vibrant colors reflecting the culture of the region.",
        "image_url": "https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=500&q=80",
        "rating": "4.50",
        "review_count": 7,
        "stock_quantity": 18,
        "category_name": "Girls Traditional Clothing",
        "category_name_ar": "ملابس البنات التقليدية",
    },
    {
        "name_ar": "الملحفة الغرداوية",
        "name": "Mlehfa Ghardaouia",
        "sku": "CH-G-006-MLG",
        "origin": "Ghardaïa · M'zab weave",
        "material": "Traditional M'zab woven fabric",
        "price": 5500,
        "old_price": None,
        "badge": "limited",
        "is_limited": True,
        "is_new": False,
        "short_description_ar": "ملحفة تقليدية من وادي ميزاب — تراث حضارة المزابيين الأصيل في غرداية.",
        "short_description": "Traditional garment from the Mzab valley — authentic heritage of the Mozabite civilization in Ghardaïa.",
        "description_ar": "الملحفة الغرداوية تعكس ثراء حضارة بني مزاب، بأنماط هندسية متناسقة ونسيج يدوي دقيق.",
        "description": "The Mlehfa Ghardaouia reflects the richness of the Beni Mzab civilization, with harmonious geometric patterns and delicate hand weaving.",
        "image_url": "https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=500&q=80",
        "rating": "4.70",
        "review_count": 5,
        "stock_quantity": 10,
        "category_name": "Girls Traditional Clothing",
        "category_name_ar": "ملابس البنات التقليدية",
    },
    {
        "name_ar": "القفطان الجزائري",
        "name": "Caftan Algérien",
        "sku": "CH-G-007-CAF",
        "origin": "Algeria · Brocade & embroidery",
        "material": "Decorative brocade",
        "price": 9800,
        "old_price": 12000,
        "badge": "sale",
        "is_new": False,
        "short_description_ar": "قفطان جزائري مزخرف للمناسبات الخاصة — أناقة التراث في قطعة واحدة.",
        "short_description": "Decorative Algerian caftan for special occasions — the elegance of heritage in one piece.",
        "description_ar": "القفطان الجزائري قطعة تراثية راقية، مزخرف بأدق التطريز وأرقى الأقمشة للمناسبات الخاصة.",
        "description": "The Algerian Caftan is a refined heritage piece, decorated with the finest embroidery and the most luxurious fabrics for special occasions.",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500&q=80",
        "rating": "4.80",
        "review_count": 14,
        "stock_quantity": 22,
        "category_name": "Girls Traditional Clothing",
        "category_name_ar": "ملابس البنات التقليدية",
    },

    # ── Boys (7) ────────────────────────────────────────────────────────────
    {
        "name_ar": "البرنوس",
        "name": "Burnous Boy",
        "sku": "CH-B-001-BRN",
        "origin": "Algeria · Wool",
        "material": "Traditional woolen fabric",
        "price": 6500,
        "old_price": None,
        "badge": "new",
        "is_new": True,
        "short_description_ar": "رداء صوفي تقليدي للأولاد — دفء ووقار في لباس واحد.",
        "short_description": "Traditional woolen cloak for boys — warmth and dignity in one garment.",
        "description_ar": "البرنوس رداء صوفي تقليدي أصيل للأولاد، يجمع بين الدفء والأناقة في المناسبات الجزائرية الكبرى.",
        "description": "The Burnous is an authentic traditional woolen cloak for boys, combining warmth and elegance for major Algerian occasions.",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80",
        "rating": "4.70",
        "review_count": 16,
        "stock_quantity": 30,
        "category_name": "Boys Traditional Clothing",
        "category_name_ar": "ملابس الأولاد التقليدية",
    },
    {
        "name_ar": "القندورة للأولاد",
        "name": "Gandoura Boy",
        "sku": "CH-B-002-GDB",
        "origin": "Algeria · Cotton",
        "material": "Cotton traditional fabric",
        "price": 3800,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "قندورة طويلة تقليدية للأولاد — راحة ومظهر تراثي أصيل.",
        "short_description": "Long traditional tunic for boys — comfort and authentic heritage look.",
        "description_ar": "القندورة لباس يومي وللمناسبات للأولاد، يتميز بتصميم بسيط وأنيق يعكس التراث الجزائري.",
        "description": "The Gandoura is a daily and occasion wear for boys, featuring a simple and elegant design reflecting Algerian heritage.",
        "image_url": "https://images.unsplash.com/photo-1597466599360-3b596c3d7cb7?w=500&q=80",
        "rating": "4.30",
        "review_count": 20,
        "stock_quantity": 45,
        "category_name": "Boys Traditional Clothing",
        "category_name_ar": "ملابس الأولاد التقليدية",
    },
    {
        "name_ar": "الجبة للأولاد",
        "name": "Jebba Boy",
        "sku": "CH-B-003-JBB",
        "origin": "Algeria · Traditional fabric",
        "material": "Traditional woven fabric",
        "price": 5200,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "رداء رسمي تقليدي للأولاد في المناسبات الدينية والاحتفالات.",
        "short_description": "Formal traditional robe for boys for religious occasions and celebrations.",
        "description_ar": "الجبة رداء تقليدي رسمي للأولاد، يُرتدى في الأعياد والمناسبات الدينية ومختلف الاحتفالات.",
        "description": "The Jebba is a formal traditional robe for boys, worn on Eid and religious occasions and various celebrations.",
        "image_url": "https://images.unsplash.com/photo-1597466599360-3b596c3d7cb7?w=500&q=80",
        "rating": "4.40",
        "review_count": 11,
        "stock_quantity": 28,
        "category_name": "Boys Traditional Clothing",
        "category_name_ar": "ملابس الأولاد التقليدية",
    },
    {
        "name_ar": "قميص وسروال عربي",
        "name": "Kamis & Seroual Arbi",
        "sku": "CH-B-004-KSA",
        "origin": "Algeria · Cotton & linen",
        "material": "Cotton and linen blend",
        "price": 4200,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "طقم القميص والسروال العربي التقليدي للأولاد — أناقة كلاسيكية وراحة ممتازة.",
        "short_description": "Traditional Arabic shirt and trousers set for boys — classic elegance and excellent comfort.",
        "description_ar": "طقم القميص والسروال العربي التقليدي الكلاسيكي للأولاد، مثالي لمختلف المناسبات والأعياد.",
        "description": "Classic traditional Arabic shirt and trousers set for boys, perfect for various occasions and celebrations.",
        "image_url": "https://images.unsplash.com/photo-1597466599360-3b596c3d7cb7?w=500&q=80",
        "rating": "4.50",
        "review_count": 25,
        "stock_quantity": 50,
        "category_name": "Boys Traditional Clothing",
        "category_name_ar": "ملابس الأولاد التقليدية",
    },
    {
        "name_ar": "العباية المزابية",
        "name": "Abaya Mzabia",
        "sku": "CH-B-005-ABM",
        "origin": "Ghardaïa · M'zab tradition",
        "material": "Traditional M'zab fabric",
        "price": 5800,
        "old_price": None,
        "badge": "limited",
        "is_limited": True,
        "is_new": False,
        "short_description_ar": "لباس تقليدي من منطقة غرداية للأولاد — تراث حضارة بني مزاب الأصيل.",
        "short_description": "Traditional garment from the Ghardaïa region for boys — authentic heritage of the Beni Mzab civilization.",
        "description_ar": "العباية المزابية لباس تقليدي نادر من تراث بني مزاب في غرداية، يتميز بتصميم فريد ونسيج يدوي دقيق.",
        "description": "The Abaya Mzabia is a rare traditional garment from the heritage of Beni Mzab in Ghardaïa, featuring a unique design and delicate hand weaving.",
        "image_url": "https://images.unsplash.com/photo-1597466599360-3b596c3d7cb7?w=500&q=80",
        "rating": "4.60",
        "review_count": 6,
        "stock_quantity": 12,
        "category_name": "Boys Traditional Clothing",
        "category_name_ar": "ملابس الأولاد التقليدية",
    },
    {
        "name_ar": "القشابية",
        "name": "Kachabia",
        "sku": "CH-B-006-KCB",
        "origin": "Algeria · Wool",
        "material": "Hooded woolen fabric",
        "price": 7500,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "معطف صوفي بغطاء رأس للأولاد — دفء تراثي من مناطق الأطلس.",
        "short_description": "Woolen hooded coat for boys — traditional warmth from the Atlas regions.",
        "description_ar": "القشابية معطف صوفي تقليدي بغطاء رأس للأولاد، يوفر الدفء في فصل الشتاء مع حفاظه على الطابع التراثي.",
        "description": "The Kachabia is a traditional woolen hooded coat for boys, providing warmth in winter while maintaining the heritage character.",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80",
        "rating": "4.50",
        "review_count": 13,
        "stock_quantity": 22,
        "category_name": "Boys Traditional Clothing",
        "category_name_ar": "ملابس الأولاد التقليدية",
    },
    {
        "name_ar": "اللباس البدوي",
        "name": "Bedoui Outfit",
        "sku": "CH-B-007-BDW",
        "origin": "Sahara · Desert tradition",
        "material": "Traditional Saharan fabric",
        "price": 6200,
        "old_price": None,
        "badge": "new",
        "is_new": True,
        "short_description_ar": "لباس صحراوي تقليدي للأولاد — أصالة الطوارق وتراث الجنوب الجزائري.",
        "short_description": "Traditional Saharan attire for boys — the authenticity of the Tuareg and the heritage of Algerian south.",
        "description_ar": "اللباس البدوي التقليدي للأولاد من تراث الجنوب الجزائري الأصيل، يعكس أصالة الطوارق وعمق حضارة الصحراء.",
        "description": "The traditional Bedoui outfit for boys from the authentic heritage of the Algerian south, reflecting the authenticity of the Tuareg and the depth of Saharan civilization.",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80",
        "rating": "4.70",
        "review_count": 8,
        "stock_quantity": 18,
        "category_name": "Boys Traditional Clothing",
        "category_name_ar": "ملابس الأولاد التقليدية",
    },

    # ── Traditional Accessories & Celebration Items (7) ────────────────────
    {
        "name_ar": "الحناء",
        "name": "Henna",
        "sku": "ACC-001-HNA",
        "origin": "Algeria · Natural",
        "material": "Natural henna powder",
        "price": 1200,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "الحناء الطبيعية للأعراس والعيد والمناسبات العائلية — زينة تراثية أصيلة.",
        "short_description": "Natural henna used during weddings, Eid, and family celebrations — authentic traditional adornment.",
        "description_ar": "الحناء الطبيعية رمز الفرح والاحتفال في التراث الجزائري، تُستخدم في الأعراس والعيد والمناسبات الخاصة.",
        "description": "Natural henna is a symbol of joy and celebration in Algerian heritage, used in weddings, Eid and special occasions.",
        "image_url": "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=500&q=80",
        "rating": "4.80",
        "review_count": 35,
        "stock_quantity": 100,
        "category_name": "Traditional Accessories & Celebration",
        "category_name_ar": "الإكسسوارات التقليدية والاحتفالية",
    },
    {
        "name_ar": "البخور",
        "name": "Bakhour",
        "sku": "ACC-002-BKH",
        "origin": "Algeria · Aromatic woods",
        "material": "Aromatic wood blend",
        "price": 1800,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "بخور تقليدي عطري — ريح الاحتفالات الجزائرية الأصيلة.",
        "short_description": "Traditional aromatic incense — the scent of authentic Algerian celebrations.",
        "description_ar": "البخور التقليدي الجزائري الأصيل، يُستخدم في المناسبات والأعراس لإضفاء عبق التراث على الأجواء.",
        "description": "Authentic traditional Algerian Bakhour, used in occasions and weddings to add the fragrance of heritage to the atmosphere.",
        "image_url": "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=500&q=80",
        "rating": "4.90",
        "review_count": 28,
        "stock_quantity": 80,
        "category_name": "Traditional Accessories & Celebration",
        "category_name_ar": "الإكسسوارات التقليدية والاحتفالية",
    },
    {
        "name_ar": "الكحل",
        "name": "Khol",
        "sku": "ACC-003-KHL",
        "origin": "Algeria · Natural minerals",
        "material": "Natural antimony",
        "price": 900,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "الكحل الطبيعي التقليدي — مستحضر تجميل تراثي جزائري أصيل.",
        "short_description": "Traditional natural kohl — authentic Algerian heritage cosmetic.",
        "description_ar": "الكحل الطبيعي التقليدي من معادن طبيعية أصيلة، مستخدم منذ آلاف السنين للزينة وحماية العينين.",
        "description": "Traditional natural kohl from authentic natural minerals, used for thousands of years for adornment and eye protection.",
        "image_url": "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=500&q=80",
        "rating": "4.70",
        "review_count": 42,
        "stock_quantity": 150,
        "category_name": "Traditional Accessories & Celebration",
        "category_name_ar": "الإكسسوارات التقليدية والاحتفالية",
    },
    {
        "name_ar": "المهراز",
        "name": "Mehrez",
        "sku": "ACC-004-MHR",
        "origin": "Algeria · Brass & copper",
        "material": "Engraved brass",
        "price": 3500,
        "old_price": None,
        "badge": "limited",
        "is_limited": True,
        "is_new": False,
        "short_description_ar": "مهراز تقليدي مزخرف يُستخدم في الاحتفالات — قطعة تراثية للزينة.",
        "short_description": "Traditional decorative mortar often used in ceremonies — a heritage decorative piece.",
        "description_ar": "المهراز التقليدي المصنوع من النحاس الأصفر المنقوش، قطعة تراثية تُستخدم في المناسبات للزينة والتقاليد الجزائرية.",
        "description": "The traditional Mehrez made from engraved brass, a heritage piece used in occasions for decoration and Algerian traditions.",
        "image_url": "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=500&q=80",
        "rating": "4.60",
        "review_count": 15,
        "stock_quantity": 20,
        "category_name": "Traditional Accessories & Celebration",
        "category_name_ar": "الإكسسوارات التقليدية والاحتفالية",
    },
    {
        "name_ar": "الحلي التقليدية",
        "name": "Traditional Jewelry",
        "sku": "ACC-005-HLY",
        "origin": "Algeria · Silver & precious stones",
        "material": "Silver with precious stones",
        "price": 15000,
        "old_price": 18000,
        "badge": "sale",
        "is_new": False,
        "short_description_ar": "حلي تقليدية جزائرية — عقود وأساور وتيجان من الفضة والأحجار الكريمة.",
        "short_description": "Traditional Algerian jewelry — necklaces, bracelets, and crowns in silver and precious stones.",
        "description_ar": "الحلي التقليدية الجزائرية الأصيلة من الفضة والأحجار الكريمة، تشمل العقود والأساور والتيجان للمناسبات الكبرى.",
        "description": "Authentic traditional Algerian jewelry in silver and precious stones, including necklaces, bracelets, and crowns for major occasions.",
        "image_url": "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=500&q=80",
        "rating": "5.00",
        "review_count": 19,
        "stock_quantity": 8,
        "category_name": "Traditional Accessories & Celebration",
        "category_name_ar": "الإكسسوارات التقليدية والاحتفالية",
    },
    {
        "name_ar": "الطربوش / الشاشية",
        "name": "Tarbouche / Chachia",
        "sku": "ACC-006-TCH",
        "origin": "Algeria · Traditional felt",
        "material": "Traditional red felt",
        "price": 2200,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "الطربوش الأحمر التقليدي — غطاء رأس كلاسيكي للمناسبات.",
        "short_description": "Traditional red fez — classic headwear for occasions.",
        "description_ar": "الطربوش أو الشاشية غطاء رأس تقليدي أيقوني في التراث الجزائري والمغاربي، يُرتدى في المناسبات الدينية والاحتفالات.",
        "description": "The Tarbouche or Chachia is an iconic traditional headwear in Algerian and Maghrebi heritage, worn on religious occasions and celebrations.",
        "image_url": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&q=80",
        "rating": "4.40",
        "review_count": 31,
        "stock_quantity": 60,
        "category_name": "Traditional Accessories & Celebration",
        "category_name_ar": "الإكسسوارات التقليدية والاحتفالية",
    },
    {
        "name_ar": "المنديل المزين",
        "name": "Mendil Mzayen",
        "sku": "ACC-007-MNZ",
        "origin": "Algeria · Embroidered silk",
        "material": "Embroidered silk scarf",
        "price": 2800,
        "old_price": None,
        "badge": "new",
        "is_new": True,
        "short_description_ar": "منديل تقليدي مطرز يُرتدى مع الأزياء الاحتفالية — لمسة تراثية راقية.",
        "short_description": "Embroidered traditional scarf worn with ceremonial outfits — a refined heritage touch.",
        "description_ar": "المنديل المزين وشاح تقليدي مطرز بأنماط جزائرية أصيلة، يُكمل الأزياء الاحتفالية ويُضيف لمسة تراثية راقية.",
        "description": "The Mendil Mzayen is an embroidered traditional scarf with authentic Algerian patterns, complementing ceremonial outfits and adding a refined heritage touch.",
        "image_url": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&q=80",
        "rating": "4.60",
        "review_count": 10,
        "stock_quantity": 35,
        "category_name": "Traditional Accessories & Celebration",
        "category_name_ar": "الإكسسوارات التقليدية والاحتفالية",
    },
]

# All category definitions with Arabic names
CATEGORY_DEFS = [
    ("Burnous", "البرنوس"),
    ("Kaftans", "القفاطين"),
    ("Djellabas", "الجلابيات"),
    ("Bridal", "الأعراس"),
    ("Accessories", "الإكسسوارات"),
    ("Footwear", "الأحذية"),
    ("Home & Decor", "الديكور والمنزل"),
    ("Girls Traditional Clothing", "ملابس البنات التقليدية"),
    ("Boys Traditional Clothing", "ملابس الأولاد التقليدية"),
    ("Traditional Accessories & Celebration", "الإكسسوارات التقليدية والاحتفالية"),
]


class Command(BaseCommand):
    help = "Seed the database with heritage and children's traditional products."

    def handle(self, *args, **options):
        # Ensure all categories exist with Arabic names
        categories = {}
        for name_en, name_ar in CATEGORY_DEFS:
            cat, created = Category.objects.get_or_create(name=name_en)
            if created or not cat.name_ar:
                cat.name_ar = name_ar
                cat.save()
            categories[name_en] = cat
            status = "Created" if created else "Updated"
            self.stdout.write(f"  {status} category: {name_ar} ({name_en})")

        created_count = 0
        skipped_count = 0

        all_products = PRODUCTS + CHILDREN_PRODUCTS

        for data in all_products:
            category = categories[data["category_name"]]
            if Product.objects.filter(sku=data["sku"]).exists():
                skipped_count += 1
                self.stdout.write(f"  Skipped (already exists): {data['name_ar'] or data['name']}")
                continue

            Product.objects.create(
                name=data["name"],
                name_ar=data.get("name_ar", ""),
                sku=data["sku"],
                category=category,
                origin=data["origin"],
                material=data["material"],
                short_description=data.get("short_description", ""),
                short_description_ar=data.get("short_description_ar", ""),
                description=data.get("description", ""),
                description_ar=data.get("description_ar", ""),
                price=data["price"],
                old_price=data.get("old_price"),
                image_url=data["image_url"],
                badge=data["badge"],
                is_new=data.get("is_new", False),
                is_limited=data.get("is_limited", False),
                rating=data["rating"],
                review_count=data["review_count"],
                stock_quantity=data["stock_quantity"],
                track_inventory=True,
                is_active=True,
            )
            created_count += 1
            self.stdout.write(f"  Created product: {data['name_ar'] or data['name']}")

        self.stdout.write(
            self.style.SUCCESS(
                f"\nDone. Created {created_count} products, skipped {skipped_count}."
            )
        )
