"""
Management command: python manage.py seed_products

Seeds the database with heritage products shown in the frontend ShopPage.
Safe to run multiple times — skips products that already exist by SKU.
"""

from django.core.management.base import BaseCommand

from apps.shop.models import Category, Product

PRODUCTS = [
    {
        "name_ar": "البرنوس العاجي الكبير",
        "sku": "BB-TLE-001-IV",
        "origin": "تلمسان · صوف خالص",
        "material": "صوف خالص 100%",
        "price": 12500,
        "old_price": None,
        "badge": "new",
        "is_new": True,
        "short_description_ar": "برنوس فاخر منسوج من أجود أصواف تلمسان، يتميز بتطريز يدوي وسقوط تراثي يُفضَّل للأعراس والمناسبات.",
        "description_ar": "برنوس فاخر منسوج من أجود أصواف تلمسان، يتميز بتطريز يدوي وسقوط تراثي يُفضَّل للأعراس والمناسبات. البرنوس هو الرداء الأصيل للمغرب — وقار ودفء وحضور لا يُضاهى.",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80",
        "stock_quantity": 50,
        "category_name_ar": "البرنوس",
    },
    {
        "name_ar": "قفطان قسنطينة الحريري",
        "sku": "BB-CON-002-SK",
        "origin": "قسنطينة · حرير خالص",
        "material": "حرير خالص",
        "price": 19800,
        "old_price": 24000,
        "badge": "sale",
        "is_new": False,
        "short_description_ar": "مطرز يدوياً بخيوط ذهبية على الطراز القسنطيني. يأتي مع حزام مطابق.",
        "description_ar": "مطرز يدوياً بخيوط ذهبية على الطراز القسنطيني التقليدي. يأتي مع حزام مطابق.",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500&q=80",
        "stock_quantity": 20,
        "category_name_ar": "القفاطين",
    },
    {
        "name_ar": "طقم الشاشية والتاقلموست",
        "sku": "BB-KAB-003-CT",
        "origin": "القبائل · صوف منسوج يدوياً",
        "material": "صوف منسوج يدوياً",
        "price": 3200,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "طقم غطاء الرأس الكامل — شاشية حمراء وتاقلموست نيلية — من نسج قبائل كاباي.",
        "description_ar": "طقم غطاء الرأس الكامل — شاشية حمراء وتاقلموست نيلية — من نسج حرفيي القبائل بأنوال لم تتغير منذ قرون.",
        "image_url": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&q=80",
        "stock_quantity": 30,
        "category_name_ar": "الإكسسوارات",
    },
    {
        "name_ar": "حزام الخدمي المزخرف",
        "sku": "BB-ANN-013-BELT",
        "origin": "عنابة · تطريز بخيط الفضة",
        "material": "خيط فضي على القطيفة",
        "price": 8900,
        "old_price": None,
        "badge": "limited",
        "is_new": False,
        "is_limited": True,
        "short_description_ar": "حزام احتفالي فاخر بخيط فضي على قطيفة برغندي، مثبّت بإبزيم محفور. قطعة نادرة للمقتنين.",
        "description_ar": "حزام احتفالي فاخر بخيط فضي على قطيفة برغندي عميق، مثبّت بإبزيم محفور. قطعة نادرة للمقتنين.",
        "image_url": "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=500&q=80",
        "stock_quantity": 5,
        "category_name_ar": "الإكسسوارات",
    },
    {
        "name_ar": "بلاغ مطرز بالذهب",
        "sku": "BB-ALG-005-BAB",
        "origin": "الجزائر العاصمة · جلد طبيعي",
        "material": "جلد طبيعي",
        "price": 4700,
        "old_price": None,
        "badge": "new",
        "is_new": True,
        "short_description_ar": "بلاغ جلدي ناعم بتطريز ذهبي يدوي على المقدمة والكعب. مريح طوال اليوم للمناسبات.",
        "description_ar": "بلاغ جلدي ناعم بتطريز ذهبي يدوي على المقدمة والكعب. مريح طوال اليوم للمناسبات الرسمية.",
        "image_url": "https://images.unsplash.com/photo-1600074169098-16a54d791d0d?w=500&q=80",
        "stock_quantity": 40,
        "category_name_ar": "الأحذية",
    },
    {
        "name_ar": "الجلابية الليلية",
        "sku": "BB-TLE-006-DJ",
        "origin": "تلمسان · مزيج صوف وقطن",
        "material": "مزيج صوف وقطن",
        "price": 9400,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "جلابية كحلية اللون بزرار مضفر يدوي وزخرفة هندسية خفية على الأكمام والياقة.",
        "description_ar": "جلابية كحلية اللون بزرار مضفر يدوي وزخرفة هندسية خفية على الأكمام والياقة.",
        "image_url": "https://images.unsplash.com/photo-1597466599360-3b596c3d7cb7?w=500&q=80",
        "stock_quantity": 25,
        "category_name_ar": "الجلابيات",
    },
    {
        "name_ar": "طقم الشدة العروسية",
        "sku": "BB-CON-007-CHE",
        "origin": "قسنطينة · قطيفة وحرير",
        "material": "قطيفة وحرير",
        "price": 32500,
        "old_price": 38000,
        "badge": "sale",
        "is_new": False,
        "short_description_ar": "طقم شدة عروس كامل يشمل البوليرو المطرز والتنورة وزينة الرأس بالذهب القسنطيني التقليدي.",
        "description_ar": "طقم شدة عروس كامل يشمل البوليرو المطرز والتنورة وزينة الرأس بالذهب القسنطيني.",
        "image_url": "https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=500&q=80",
        "stock_quantity": 10,
        "category_name_ar": "الأعراس",
    },
    {
        "name_ar": "سجادة صلاة غرداوية",
        "sku": "BB-GHA-008-RUG",
        "origin": "غرداية · صوف معقود يدوياً",
        "material": "صوف معقود يدوياً",
        "price": 16200,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "سجادة صلاة موزابية بأنماط هندسية في صوف طبيعي غير مصبوغ، من نسج حرفيي غرداية.",
        "description_ar": "سجادة صلاة موزابية بأنماط هندسية في صوف طبيعي غير مصبوغ، من نسج حرفيي بني ميزاب في غرداية.",
        "image_url": "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&q=80",
        "stock_quantity": 15,
        "category_name_ar": "الديكور والمنزل",
    },
    {
        "name_ar": "الحايك المطرز",
        "sku": "BB-ALG-009-HAI",
        "origin": "الجزائر العاصمة · قطن ناعم",
        "material": "قطن ناعم",
        "price": 5600,
        "old_price": None,
        "badge": "new",
        "is_new": True,
        "short_description_ar": "حايك مطرز بقطن ناعم أبيض مع حواف زهرية رقيقة، مثالي للمناسبات الرسمية.",
        "description_ar": "حايك مطرز بقطن ناعم أبيض مع حواف زهرية رقيقة، مثالي للمناسبات الرسمية.",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80",
        "stock_quantity": 35,
        "category_name_ar": "الإكسسوارات",
    },
]

CHILDREN_PRODUCTS = [
    {
        "name_ar": "قندورة الكاراكو",
        "sku": "CH-G-001-KRK",
        "origin": "الجزائر العاصمة · قطيفة وتطريز",
        "material": "قطيفة مع تطريز ذهبي",
        "price": 8500,
        "old_price": None,
        "badge": "new",
        "is_new": True,
        "short_description_ar": "لباس تقليدي مطرز بالذهب على القطيفة — الكاراكو الأصيل للبنات في المناسبات الكبرى.",
        "description_ar": "الكاراكو قطعة تراثية جزائرية أصيلة، مطرزة يدوياً بخيوط ذهبية على قطيفة فاخرة. مثالي للأعراس والأعياد.",
        "image_url": "https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=500&q=80",
        "stock_quantity": 20,
        "category_name_ar": "ملابس البنات التقليدية",
    },
    {
        "name_ar": "الشدة التلمسانية",
        "sku": "CH-G-002-CHT",
        "origin": "تلمسان · حرير وبروكار",
        "material": "حرير وبروكار",
        "price": 12000,
        "old_price": 15000,
        "badge": "sale",
        "is_new": False,
        "short_description_ar": "لباس احتفالي تقليدي مستوحى من تراث تلمسان — للبنات في المناسبات.",
        "description_ar": "الشدة التلمسانية من أرقى الألبسة التقليدية الجزائرية، تجمع بين فخامة الحرير وروعة التطريز.",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80",
        "stock_quantity": 15,
        "category_name_ar": "ملابس البنات التقليدية",
    },
    {
        "name_ar": "البلوزة الوهرانية",
        "sku": "CH-G-003-BLW",
        "origin": "وهران · قماش مطرز",
        "material": "مزيج قطن وحرير مطرز",
        "price": 7200,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "فستان أنيق من وهران بتطريز جميل — يعكس تراث المدينة الساحلية الجميلة.",
        "description_ar": "البلوزة الوهرانية لباس تقليدي أنيق يجمع بين الجمال والتراث الأصيل لمدينة وهران.",
        "image_url": "https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=500&q=80",
        "stock_quantity": 25,
        "category_name_ar": "ملابس البنات التقليدية",
    },
    {
        "name_ar": "القندورة",
        "sku": "CH-G-004-GND",
        "origin": "الجزائر · قطن مطرز",
        "material": "قطن خفيف مطرز",
        "price": 4500,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "قندورة خفيفة مطرزة للبنات — راحة وأناقة في لباس واحد.",
        "description_ar": "القندورة لباس تقليدي كلاسيكي للبنات، خفيف ومريح مع تطريز يدوي جميل.",
        "image_url": "https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=500&q=80",
        "stock_quantity": 40,
        "category_name_ar": "ملابس البنات التقليدية",
    },
    {
        "name_ar": "الجبة الفرقانية",
        "sku": "CH-G-005-DJF",
        "origin": "قسنطينة · قماش تقليدي",
        "material": "قماش تقليدي منسوج",
        "price": 6800,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "لباس تقليدي قسنطيني أصيل للبنات — يحمل روح مدينة الجسور المعلقة.",
        "description_ar": "الجبة الفرقانية من تراث قسنطينة العريق، تتميز بتطريز دقيق وألوان زاهية تعكس ثقافة المنطقة.",
        "image_url": "https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=500&q=80",
        "stock_quantity": 18,
        "category_name_ar": "ملابس البنات التقليدية",
    },
    {
        "name_ar": "الملحفة الغرداوية",
        "sku": "CH-G-006-MLG",
        "origin": "غرداية · نسيج مزابي",
        "material": "قماش مزابي تقليدي منسوج",
        "price": 5500,
        "old_price": None,
        "badge": "limited",
        "is_limited": True,
        "is_new": False,
        "short_description_ar": "ملحفة تقليدية من وادي ميزاب — تراث حضارة المزابيين الأصيل في غرداية.",
        "description_ar": "الملحفة الغرداوية تعكس ثراء حضارة بني مزاب، بأنماط هندسية متناسقة ونسيج يدوي دقيق.",
        "image_url": "https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=500&q=80",
        "stock_quantity": 10,
        "category_name_ar": "ملابس البنات التقليدية",
    },
    {
        "name_ar": "القفطان الجزائري",
        "sku": "CH-G-007-CAF",
        "origin": "الجزائر · بروكار وتطريز",
        "material": "بروكار مزخرف",
        "price": 9800,
        "old_price": 12000,
        "badge": "sale",
        "is_new": False,
        "short_description_ar": "قفطان جزائري مزخرف للمناسبات الخاصة — أناقة التراث في قطعة واحدة.",
        "description_ar": "القفطان الجزائري قطعة تراثية راقية، مزخرف بأدق التطريز وأرقى الأقمشة للمناسبات الخاصة.",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500&q=80",
        "stock_quantity": 22,
        "category_name_ar": "ملابس البنات التقليدية",
    },
    {
        "name_ar": "البرنوس",
        "sku": "CH-B-001-BRN",
        "origin": "الجزائر · صوف",
        "material": "قماش صوفي تقليدي",
        "price": 6500,
        "old_price": None,
        "badge": "new",
        "is_new": True,
        "short_description_ar": "رداء صوفي تقليدي للأولاد — دفء ووقار في لباس واحد.",
        "description_ar": "البرنوس رداء صوفي تقليدي أصيل للأولاد، يجمع بين الدفء والأناقة في المناسبات الجزائرية الكبرى.",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80",
        "stock_quantity": 30,
        "category_name_ar": "ملابس الأولاد التقليدية",
    },
    {
        "name_ar": "القندورة للأولاد",
        "sku": "CH-B-002-GDB",
        "origin": "الجزائر · قطن",
        "material": "قماش قطني تقليدي",
        "price": 3800,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "قندورة طويلة تقليدية للأولاد — راحة ومظهر تراثي أصيل.",
        "description_ar": "القندورة لباس يومي وللمناسبات للأولاد، يتميز بتصميم بسيط وأنيق يعكس التراث الجزائري.",
        "image_url": "https://images.unsplash.com/photo-1597466599360-3b596c3d7cb7?w=500&q=80",
        "stock_quantity": 45,
        "category_name_ar": "ملابس الأولاد التقليدية",
    },
    {
        "name_ar": "الجبة للأولاد",
        "sku": "CH-B-003-JBB",
        "origin": "الجزائر · قماش تقليدي",
        "material": "قماش تقليدي منسوج",
        "price": 5200,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "رداء رسمي تقليدي للأولاد في المناسبات الدينية والاحتفالات.",
        "description_ar": "الجبة رداء تقليدي رسمي للأولاد، يُرتدى في الأعياد والمناسبات الدينية ومختلف الاحتفالات.",
        "image_url": "https://images.unsplash.com/photo-1597466599360-3b596c3d7cb7?w=500&q=80",
        "stock_quantity": 28,
        "category_name_ar": "ملابس الأولاد التقليدية",
    },
    {
        "name_ar": "قميص وسروال عربي",
        "sku": "CH-B-004-KSA",
        "origin": "الجزائر · قطن وكتان",
        "material": "مزيج قطن وكتان",
        "price": 4200,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "طقم القميص والسروال العربي التقليدي للأولاد — أناقة كلاسيكية وراحة ممتازة.",
        "description_ar": "طقم القميص والسروال العربي التقليدي الكلاسيكي للأولاد، مثالي لمختلف المناسبات والأعياد.",
        "image_url": "https://images.unsplash.com/photo-1597466599360-3b596c3d7cb7?w=500&q=80",
        "stock_quantity": 50,
        "category_name_ar": "ملابس الأولاد التقليدية",
    },
    {
        "name_ar": "العباية المزابية",
        "sku": "CH-B-005-ABM",
        "origin": "غرداية · تقاليد مزابية",
        "material": "قماش مزابي تقليدي",
        "price": 5800,
        "old_price": None,
        "badge": "limited",
        "is_limited": True,
        "is_new": False,
        "short_description_ar": "لباس تقليدي من منطقة غرداية للأولاد — تراث حضارة بني مزاب الأصيل.",
        "description_ar": "العباية المزابية لباس تقليدي نادر من تراث بني مزاب في غرداية، يتميز بتصميم فريد ونسيج يدوي دقيق.",
        "image_url": "https://images.unsplash.com/photo-1597466599360-3b596c3d7cb7?w=500&q=80",
        "stock_quantity": 12,
        "category_name_ar": "ملابس الأولاد التقليدية",
    },
    {
        "name_ar": "القشابية",
        "sku": "CH-B-006-KCB",
        "origin": "الجزائر · صوف",
        "material": "قماش صوفي بغطاء رأس",
        "price": 7500,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "معطف صوفي بغطاء رأس للأولاد — دفء تراثي من مناطق الأطلس.",
        "description_ar": "القشابية معطف صوفي تقليدي بغطاء رأس للأولاد، يوفر الدفء في فصل الشتاء مع حفاظه على الطابع التراثي.",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80",
        "stock_quantity": 22,
        "category_name_ar": "ملابس الأولاد التقليدية",
    },
    {
        "name_ar": "اللباس البدوي",
        "sku": "CH-B-007-BDW",
        "origin": "الصحراء · تقاليد صحراوية",
        "material": "قماش صحراوي تقليدي",
        "price": 6200,
        "old_price": None,
        "badge": "new",
        "is_new": True,
        "short_description_ar": "لباس صحراوي تقليدي للأولاد — أصالة الطوارق وتراث الجنوب الجزائري.",
        "description_ar": "اللباس البدوي التقليدي للأولاد من تراث الجنوب الجزائري الأصيل، يعكس أصالة الطوارق وعمق حضارة الصحراء.",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80",
        "stock_quantity": 18,
        "category_name_ar": "ملابس الأولاد التقليدية",
    },
    {
        "name_ar": "الحناء",
        "sku": "ACC-001-HNA",
        "origin": "الجزائر · طبيعي",
        "material": "مسحوق الحناء الطبيعي",
        "price": 1200,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "الحناء الطبيعية للأعراس والعيد والمناسبات العائلية — زينة تراثية أصيلة.",
        "description_ar": "الحناء الطبيعية رمز الفرح والاحتفال في التراث الجزائري، تُستخدم في الأعراس والعيد والمناسبات الخاصة.",
        "image_url": "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=500&q=80",
        "stock_quantity": 100,
        "category_name_ar": "الإكسسوارات التقليدية والاحتفالية",
    },
    {
        "name_ar": "البخور",
        "sku": "ACC-002-BKH",
        "origin": "الجزائر · أخشاب عطرية",
        "material": "مزيج أخشاب عطرية",
        "price": 1800,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "بخور تقليدي عطري — ريح الاحتفالات الجزائرية الأصيلة.",
        "description_ar": "البخور التقليدي الجزائري الأصيل، يُستخدم في المناسبات والأعراس لإضفاء عبق التراث على الأجواء.",
        "image_url": "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=500&q=80",
        "stock_quantity": 80,
        "category_name_ar": "الإكسسوارات التقليدية والاحتفالية",
    },
    {
        "name_ar": "الكحل",
        "sku": "ACC-003-KHL",
        "origin": "الجزائر · معادن طبيعية",
        "material": "أثمد طبيعي",
        "price": 900,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "الكحل الطبيعي التقليدي — مستحضر تجميل تراثي جزائري أصيل.",
        "description_ar": "الكحل الطبيعي التقليدي من معادن طبيعية أصيلة، مستخدم منذ آلاف السنين للزينة وحماية العينين.",
        "image_url": "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=500&q=80",
        "stock_quantity": 150,
        "category_name_ar": "الإكسسوارات التقليدية والاحتفالية",
    },
    {
        "name_ar": "المهراز",
        "sku": "ACC-004-MHR",
        "origin": "الجزائر · نحاس أصفر ونحاس أحمر",
        "material": "نحاس أصفر منقوش",
        "price": 3500,
        "old_price": None,
        "badge": "limited",
        "is_limited": True,
        "is_new": False,
        "short_description_ar": "مهراز تقليدي مزخرف يُستخدم في الاحتفالات — قطعة تراثية للزينة.",
        "description_ar": "المهراز التقليدي المصنوع من النحاس الأصفر المنقوش، قطعة تراثية تُستخدم في المناسبات للزينة والتقاليد الجزائرية.",
        "image_url": "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=500&q=80",
        "stock_quantity": 20,
        "category_name_ar": "الإكسسوارات التقليدية والاحتفالية",
    },
    {
        "name_ar": "الحلي التقليدية",
        "sku": "ACC-005-HLY",
        "origin": "الجزائر · فضة وأحجار كريمة",
        "material": "فضة مع أحجار كريمة",
        "price": 15000,
        "old_price": 18000,
        "badge": "sale",
        "is_new": False,
        "short_description_ar": "حلي تقليدية جزائرية — عقود وأساور وتيجان من الفضة والأحجار الكريمة.",
        "description_ar": "الحلي التقليدية الجزائرية الأصيلة من الفضة والأحجار الكريمة، تشمل العقود والأساور والتيجان للمناسبات الكبرى.",
        "image_url": "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=500&q=80",
        "stock_quantity": 8,
        "category_name_ar": "الإكسسوارات التقليدية والاحتفالية",
    },
    {
        "name_ar": "الطربوش / الشاشية",
        "sku": "ACC-006-TCH",
        "origin": "الجزائر · لباد تقليدي",
        "material": "لباد أحمر تقليدي",
        "price": 2200,
        "old_price": None,
        "badge": "",
        "is_new": False,
        "short_description_ar": "الطربوش الأحمر التقليدي — غطاء رأس كلاسيكي للمناسبات.",
        "description_ar": "الطربوش أو الشاشية غطاء رأس تقليدي أيقوني في التراث الجزائري والمغاربي، يُرتدى في المناسبات الدينية والاحتفالات.",
        "image_url": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&q=80",
        "stock_quantity": 60,
        "category_name_ar": "الإكسسوارات التقليدية والاحتفالية",
    },
    {
        "name_ar": "المنديل المزين",
        "sku": "ACC-007-MNZ",
        "origin": "الجزائر · حرير مطرز",
        "material": "وشاح حريري مطرز",
        "price": 2800,
        "old_price": None,
        "badge": "new",
        "is_new": True,
        "short_description_ar": "منديل تقليدي مطرز يُرتدى مع الأزياء الاحتفالية — لمسة تراثية راقية.",
        "description_ar": "المنديل المزين وشاح تقليدي مطرز بأنماط جزائرية أصيلة، يُكمل الأزياء الاحتفالية ويُضيف لمسة تراثية راقية.",
        "image_url": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&q=80",
        "stock_quantity": 35,
        "category_name_ar": "الإكسسوارات التقليدية والاحتفالية",
    },
]

CATEGORY_DEFS = [
    "البرنوس",
    "القفاطين",
    "الجلابيات",
    "الأعراس",
    "الإكسسوارات",
    "الأحذية",
    "الديكور والمنزل",
    "ملابس البنات التقليدية",
    "ملابس الأولاد التقليدية",
    "الإكسسوارات التقليدية والاحتفالية",
]


class Command(BaseCommand):
    help = "Seed the database with heritage and children's traditional products."

    def handle(self, *args, **options):
        categories = {}
        for name_ar in CATEGORY_DEFS:
            cat, created = Category.objects.get_or_create(name_ar=name_ar)
            categories[name_ar] = cat
            status = "Created" if created else "Found"
            self.stdout.write(f"  {status} category: {name_ar}")

        created_count = 0
        skipped_count = 0

        for data in PRODUCTS + CHILDREN_PRODUCTS:
            if Product.objects.filter(sku=data["sku"]).exists():
                skipped_count += 1
                self.stdout.write(f"  Skipped (already exists): {data['name_ar']}")
                continue

            Product.objects.create(
                name_ar=data["name_ar"],
                sku=data["sku"],
                category=categories[data["category_name_ar"]],
                origin=data["origin"],
                material=data["material"],
                short_description_ar=data.get("short_description_ar", ""),
                description_ar=data.get("description_ar", ""),
                price=data["price"],
                old_price=data.get("old_price"),
                image_url=data["image_url"],
                badge=data["badge"],
                is_new=data.get("is_new", False),
                is_limited=data.get("is_limited", False),
                stock_quantity=data["stock_quantity"],
                track_inventory=True,
                is_active=True,
            )
            created_count += 1
            self.stdout.write(f"  Created product: {data['name_ar']}")

        self.stdout.write(
            self.style.SUCCESS(
                f"\nDone. Created {created_count} products, skipped {skipped_count}."
            )
        )
